---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ceph-csi-rbd
    chart: ceph-csi-rbd-2.1.2-canary
    component: nodeplugin
    heritage: Helm
    release: ceph-csi-rbd
  name: ceph-csi-rbd-nodeplugin-http-metrics
  namespace: ceph-csi-rbd
spec:
  ports:
  - name: http-metrics
    port: 8080
    targetPort: 8080
  selector:
    app: ceph-csi-rbd
    component: nodeplugin
    release: ceph-csi-rbd
  type: ClusterIP
