---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: ceph-csi-rbd
    chart: ceph-csi-rbd-2.1.2-canary
    component: provisioner
    heritage: Helm
    release: ceph-csi-rbd
  name: ceph-csi-rbd-provisioner
  namespace: ceph-csi-rbd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ceph-csi-rbd-provisioner
subjects:
- kind: ServiceAccount
  name: ceph-csi-rbd-provisioner
  namespace: ceph-csi-rbd
