---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ceph-csi-rbd
    chart: ceph-csi-rbd-2.1.2-canary
    component: provisioner
    heritage: Helm
    release: ceph-csi-rbd
  name: ceph-csi-rbd-provisioner
  namespace: ceph-csi-rbd
