apiVersion: v1
kind: Secret
metadata:
    name: authsecret
    namespace: traefik
data:
    users: ENC[AES256_GCM,data:+lrp0ChqMP7Nxyi76UseqxyM/OLCh8bA0CQdhoFVgUKQ3u8COn3pi1bSxo5Vxc1AbrknmnTcjcX5IUdYg2oj+g==,iv:ze8h7Jn2nlzBHbAwEy4l5FVBXlvfjQoYlM6iA+yQGNU=,tag:x1uYU7ebzs42QYvb2eIkCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-07-04T15:54:25Z'
    mac: ENC[AES256_GCM,data:mU/HkNNON4vtoW0gbTBbO0ecgNfNYGturd4PoNDc5xOLBlT3az9EvCdIbNgW0QUIdKOZQlF/lgSqW1Givl+LDVaib3fIOQXphhvBLUgHuDGRaVkJM+x4Xido/6qdCs8mum+sWLMjLED8sxfIi9PQol39EEPUJSVEYTzkkarqgFI=,iv:r0aUXZwmYobUzualQP3XTuyp8bCNVgZ0I42nvL52kIg=,tag:Y/xNoAJyBUtOkWYqPaTaGQ==,type:str]
    pgp:
    -   created_at: '2020-07-04T15:54:24Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA8+hman75/nUARAAu6OuBrCMfkQLDqtSkSf0QIZKiofizc2WtJkaFyOEDoIM
            KTuSQq8pqO8UEvT9PvYwtn77miPthfJ/7JAknyd6w02t16mMa7kp4weOL6kQiyEb
            2iCNydSRT5VLK3Juk5sV7qfmGq1IuOjDstwkQ+XdHsgGLh5WqGxKCf29V8zuK29g
            4gpYzv+45v6ozZm8M3TDWJMBCt3VtKBty3RbBa1L3S3p3yah2jCo98/aLDEE0yym
            F5EuKcNicFJS9C3FEsJglNw4OZf1lRiSLVWy0Szb44/Q8soxDVCu6pCtLHUEoYEU
            llpWe2N5RPfyEXpZL+FsNDviW0BjJIuZzLZbV2OGNeDf9klployiOL8rwWACrcRN
            r8o28XX5lbJ2Xu+yBmmHVVpydJc8XDAVA6ipBllOkecFJBng7tYdb1wBbKQyqL2y
            EkekBBCwPLXUJglTsIfwPEEXYtLyQ3rAr4uCr1nuUiQqp1HzWnjY8A0NeiKJLwfU
            VeCCcEKIQLYrsBYZZxyk5S0c7QV+dy4zwegG+PQaeYYMqaDnIlMZRAhpdZXTyPKM
            0US4iS0qndxIV5kOiyj0iP7HkY/ND9mUVoYEfTlWxSbp55vls0e4TFe1DSNUHEcL
            CZepCGhayZb7bQko+z3DOFWjgGDQiRzoCi+E3d7D2Rx0WtlSsZnrkZMXfgubaC/S
            4AHkOAOLP/KevQA7NoJCclgxTOHFquAP4KzhVzDgTeK8wHbz4GblUdlERF3qdbgh
            Ptid91g52+mLRijWLos6LKxFnkYYqsvgYOTK5T/OD413fdakdDL6XZYX4vA7ZSbh
            AEQA
            =gLms
            -----END PGP MESSAGE-----
        fp: 211FA1AE58F975F266A3E42E3CF239734CDBFD58
    encrypted_regex: (.*secret.*|.*password.*|.*users.*)
    version: 3.5.0
