apiVersion: v1
kind: Secret
metadata:
    name: authsecret
    namespace: traefik
data:
    users: ENC[AES256_GCM,data:e3XDj0uJlCfhCj0jF15c+/0r9FzGJeQcMbrkaigLrC3E45iiL9rwklj28C8+5KesvSqHagk3WyZo+WZaSIwSOQ==,iv:nzkd3zuQjL6YY0zU6wIzYsSqQ0ZyMpQuE/tmA+TBKq4=,tag:KG7yyq0zEIqmuKL8WHJyrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-09-08T01:57:57Z'
    mac: ENC[AES256_GCM,data:uJmjLdvjW3xrhRJVqrrUJMaTjHDZzTUOI764laC5tiD3j3PhLFuUpFanGp+dsSaXdN5nT4yMzMyRepOtDAn7F5ni7m5PIpGuzomNMAI9b7jbukfkSITNXYJ+EajU7Osk9/Hp4fiv18rAZdM1vtDu8cWPJBs1bKHmVvGaH/+dxYI=,iv:c94Zd8XbHDB89bVxasKR0wyntf6sVLQ8+gRnc8sTb+Q=,tag:H6PhLmll027l/dinhLPI4w==,type:str]
    pgp:
    -   created_at: '2020-09-08T01:57:57Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8+hman75/nUARAAxUQlQto6ehzDcTMSHqzzX+NUxrYyzrp9mJKmiHh8XLqM
            Mk4bWM77F2RHSmT8u/3sUWUN27+Ka9zJuwu0BWje7845pNj3f07i4W8Uy/R+tBds
            OoHTrll7hZWRaRnrTOr5loDBJLxn+WOFoDsO6P4n7pCy/xw29M4ZiuDhEryVcZIF
            7C2bq5iHCr9kprkQGD3TY1lX2fbiM7xpBaNeTtnMb0aBbLwZle6ukwTTC185qWZi
            DWT+oCgBysR9a4K1OvGvyZa89cajMte0e2Von4D8UGIGTTz5RRXSAF9KYLph32MO
            rT+xga2c7CN6IslQRAXveDGLh9/Mzc1gHYUz9z9zKQ9Ig5MXuuuyQc8giASXVqSu
            lgRbyX1Imv8HryELfxqToPalNRo1QS+Gz3RC+qv8NgwSewhaAlWPfIju9mrmhqJ2
            GhbDM3w81n2jObAM14FIfYRMfyOBa9Kj/aEgpTaHExDvkyWgDAGUbUSoZl8+Y3np
            D3hqFZ6p0qFj1Y64VkucGMm1pXhN/c6aEC5+w6BEc/ETHdE9RPe87Ge5Qbao4QDk
            SmPs93yMoIgIb7ggpTp0511LC/ZaXijcNbLC+R+VcymeSnObLDi388UjRfllZ7BF
            ChviTZt5179MttEcRC2l5/YMNHyzPVVAZOrySRYfI53P70KeLUGu8vAQ99XqU3LS
            XAEshEz+233WS3JgMzuX4WI7kfGiFm4uA0pim5BSfVPnnw+a0s/yiWI83EGEhFh9
            x8AumlythMk8VwzhA6ZetjOzC2yXD4YcQpGUTZTIW9GgLeMbwoLqZUC8O06m
            =gSrd
            -----END PGP MESSAGE-----
        fp: 211FA1AE58F975F266A3E42E3CF239734CDBFD58
    encrypted_regex: (.*secret.*|.*password.*|.*user.*|.*admin.*)
    version: 3.5.0
