apiVersion: v1
kind: Secret
metadata:
    name: authsecret
    namespace: traefik
data:
    users: ENC[AES256_GCM,data:TUeJYH0WVNV1YOfLMZaTaC22323/pfnUoOaG4A7Nr/QvGEKIvdjA9V0hN424BeW5iZKmgEeldW8q5j7oBW/HaQ==,iv:1xHio0r6HGPOvNBNeP9s69+y7AZ54PEyuJzne4Yx6Mw=,tag:ZW10zp2bd8tcQw7/Nv/MTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-07-02T02:20:11Z'
    mac: ENC[AES256_GCM,data:I2lcjQvS0PD8o5pVHy3Lt6ERxRRv+SwHUo6PWyyjtx/qit43g9MmKg54Q736k/lw46IUhrTTVrgg3lN7Lfi5gKge6jmB/vuT2ISFk6p1lh7o7IsIY8ZYkTNOaJUHngdqS9WNK0bmZtbGa5/fyJ4SFZT7SPP+xh4gaUSwAgn9n/E=,iv:WC/RZpXujYc61wIjAzFwH9e5VIxIvz+9PV7BWLrzQvw=,tag:YumwKpjeRdD8LD+6DuYCSQ==,type:str]
    pgp:
    -   created_at: '2020-07-02T02:20:11Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA8+hman75/nUARAAG154I69oNnK/uBLhCSG9f4BwzMVxSCRU7k0Tptshy6tP
            qYPtm8mj+BRfSletoOWkYqkdGc4p5OehmZNFPkr3ZDTlf49CVB8Y0wCr8dP1SP6b
            /pyPQ2cDkK9/G1l2zuHGQH4L+NA3/i7C6Hur5no4kJk6qCqBK3bPqac+OJfZWanF
            sT/p8KLHYbDczQK3M4tRFFYNcni9o6mlICzPU6fksqbCdti1DO4AFrOgLX/htMPp
            bh9KpR7Z1SSoZGnxhdnHNmnmueElsMish0Sc+NIZ3mQOmWwbmZDiYRua4GZSvjiI
            g96LOy0eJw61fun+8Vf9nhfw2yMOC1dfT7az7V9WvIBthgrhlbH55yd2olOYnmzw
            KAV/Sij2Hwk2lsf2mQeTNbrnfx9dcFfdYrUkJFoROgkrY9obgqTkNAgMh8TVnnhf
            7ls8aA9fdO9LeUuFbZgVtcI0tsujZbQJQ+kJLJyNde/8nhUUdVo4BA3P+HgdTtLK
            TVh/za5OMAS9y6kPWNDIVwwRzogHpVTmarQpcav45S4T10VMeU0m/wQ4b4yc0EM/
            0yBuIT9vRDetzFyhkXKuOD5R1r3zVX99IaluPyDSMUAQbFPqkHJsn4AuGDRCCf5F
            LQ9/HxvdLrX8LtZTUAxD77wuR0lhUoHt8o+dsDpDSPVEb+78a5LZWnwDci5DQhjS
            4AHkNBfwTnrv67hQ+3g1mflCUeHXPeAP4Avhqnvg++LD/PL24CPlbhg5xuZRvVZp
            fdXve0Bj8/AATd+oKbo1NfC2APYI4TfggOQyB8zZktMUjEHTqoQZ+Rwt4ktGOafh
            m8sA
            =f1ET
            -----END PGP MESSAGE-----
        fp: 211FA1AE58F975F266A3E42E3CF239734CDBFD58
    encrypted_regex: (.*secret.*|.*password.*|.*users.*)
    version: 3.5.0
