apiVersion: ENC[AES256_GCM,data:S+s=,iv:LBaUlVRpt7S2tSJpYeB4Hnhn9m2XY7l8D30X+8eaxlk=,tag:RJmsG9AHrBtPY2PCufoxcQ==,type:str]
kind: ENC[AES256_GCM,data:C3nu5s6X,iv:OoWT0Nnp574wcf0r8I7sfCp6ahq+ilmbe5xK/6YIk7g=,tag:h15rZOJiXNrES1+5gUKCxg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Y3tz0qjlfWoA/A==,iv:Hdwwmc4i+pVYfq4z6Lslc0VgJTkiXNhuhWbqhaO34PM=,tag:45KHtg/X3Scte/41Jaf0nw==,type:str]
    namespace: ENC[AES256_GCM,data:Te15JLkRBg==,iv:ERVtm0AhkWAi6aJ2eyvkS5bdV4sRWi1r1djaCpRnwGQ=,tag:cF6VqHxi4RzcyNjLBj1JJQ==,type:str]
data:
    users: ENC[AES256_GCM,data:glPm6+zVkqfMWZ1M/Y2lRJ2qjIXa7xRcCpcKvPasfLl+YVkqeMiMrOnsnbufZpQvaS195FKrt8uX3Oab0Aob7A==,iv:Y41YsSYUb4DB4psKYZYR12LfxYMFQ1xoMrEPeXTyGhA=,tag:sPRXVjajovpr//WbwRuiFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-09-08T21:28:56Z'
    mac: ENC[AES256_GCM,data:LEvhEwtgU6WPW7ODxct8BHmQVkm73A3cFvcghckXEngKqDFrGeBqpc2RUJP7p4lCG28I/jUdPMFbz66ggdJw3JEMXE7Vlnq/WNMQcA/fXMgIpZVluGYg+otx90uY/j+VbJO6v16iKsJjcGr7UfKhrwq9faEXVZ9+5qLwHcCIkdg=,iv:xCfvoaFEHs5wqB6cLMAPC6Jwux0ovQyxZf/GBpcvhRI=,tag:1RdG/19SZEQJ9Rrf85mSCg==,type:str]
    pgp:
    -   created_at: '2020-09-08T21:28:56Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQILA8+hman75/nUAQ/42xTe/cKFnOo4+EEEPr8KUHMdUzQyH20JY4upQT4+LxIq
            EfYUwN/qrDuDo+H0sEe1v9AREy0tcjW9n83MISRmtycWvbkB/XCICA7WSSOvgH7a
            gNkDDAW0Cbj/dve14nLJQMiT4dkZLZ3l08AIrZACSog0L22UVq6eGFo3KBtpSrpJ
            +/GORNkrpDQA30h/8Z5QlIl/Gpl6Im4maMTZ/C36Jgx83M5KP6khcuBwdG2tAvG6
            i6hB1lP5oVu5fj9J4crMZm4UCvBlMPdm4prbYLiLegpyyYJyKr+GwKZxmtSZd+r1
            SsGTF70SNABZPXRDhvFRdYLJwMCFSQ2oBjuzvOU6zR2BXuCzAwPz8IR8vIxeAKT2
            jvYvNlk2njR6eZMRCxLKHtLAaoR3Xl9O9y2Z5eLL05sDiBsDEMjGd7Y5EdcgvmIq
            86VoBgzaeBfVGAL3+HhqyVA4ttysUF66mEtApTzQgMsR9s4gX78qlbpMClsa1LYO
            xxTp9G2OpoH5GdMoXzVmDvwR6h/pmcNyJ1KhTz5TrThqjs95jaI1TW+ccnEdqpg+
            f7t8wrSTddbt8JP4a+dqd7BZSTU2QIVt4lB5um7Q4VRAy9pDPaXoae8KWICAhy6Y
            eyyd/Xp1YZ5OC5TVP3mhfNJsJsJwLnLYlm89aq9dzowX1EGxB4cBum3WwkIsT9Je
            AXSOxYxH/FYz/NN3z7h/b0eehc0I6Qd2YEfd3mkvqVhBsfdGnurR7dJf5oHlvq/f
            ZYFhqjAtbnFuBV3UposArMrZAOFfL3CZHm2NkhEu4F8/uMAlvYNonrGLUHbUfA==
            =/+kO
            -----END PGP MESSAGE-----
        fp: 211FA1AE58F975F266A3E42E3CF239734CDBFD58
    unencrypted_suffix: _unencrypted
    version: 3.5.0
