apiVersion: v1
kind: Secret
metadata:
    name: authsecret
    namespace: traefik
data:
    users: ENC[AES256_GCM,data:lugWVFXFMG5I4OXzB4z0zEDGHGAlDKmaPzVD18wc6Z+CHcrGhcemMSJ/VnsnVNE33mhIGyYnwQney2LpHbnGSQ==,iv:vQ23Dao1QC/kYeI2tzysnzrCgLa/tVc077NnFh0s0cg=,tag:diIOx3duKAGJSIx8/cVw+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-07-03T18:15:32Z'
    mac: ENC[AES256_GCM,data:awVpiS9jl+14ctz42aQOMCYM2hEBZXzzzcAkM8aUfWnb6m7QXvGjqWr6rE8u231wwEx1I6pj5hBSIsuK2pnVrvqx5f/QPg8+aK5SuXhob3rjUOYomoj5kak8KclSsUly8Zqzd+IvF/wAor71rtYmD2etY8g+399jvrILbAAi2yE=,iv:oUeWw1zbxSXo5rY6qcx4vGBzHOUDnElV7ejgwX4cdYo=,tag:fLgQj54LJDllK8EwMmXNiw==,type:str]
    pgp:
    -   created_at: '2020-07-03T18:15:32Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA8+hman75/nUARAAOz/2kS/1T9i7yaJIlxC2Q1fptnlkcme/lM73+zhVcpHI
            BKwXI4nojQfTXHkP+vqe7s98gkbTIZlM0L8/vI7AsLWhwhqvYGSgKpz3vuESaAiT
            nzB4Zl50fwtBaeu29XprewYjQNjmNKhT8BWQco0lZeKscy+ypN2TB/fCzhBjGqa6
            nroL9MjL1cE2WZ3elRg44PP5Yw3KOPTcchTvTbLWUDp1Gly96UY3g3yDNbrDhR2Q
            jxJxi33OPmDce+IWA+wLqH3XfjRPt4HaFjL5xoSb83NfoO/0Jo/gNUzy+n6ApXQe
            ItPWFc7G1xt8+knjkV8h7q4cr5I3Mcrc3c8TUCRtNltceT6eilYVI0MxUMhH4+WK
            FZqTiUkblNi6LlcJmrSPMKkFxM7dousEsB0KagAaDFPTmbvT6KnzIQCIp9WhhQNz
            oLVYKfQK7CITlKecUXgsqlj/bh2bKcUsQPpzDaDxm532LRdvm/3jNNci1uOVqq8S
            8u4VpjfIRftlEZPoZpdYfbuK+YQQvaQEpUWHgREF4eFRcWNsYi355uGSkg9+/QBN
            sv3ReEHSsJKO0vIpvKMj3pT3tzWff8ceH2gkEMOEkzb1UX0SeDUMY57MGrfKPX5q
            OmmMaURv6nJ/qv5adzpSVuaZyokykCF1yH2g0PvFZoz/x+Nvz+5hBaoKvl+Ww/nS
            4AHkcf74KtJ6OIo+Oz8oRbniyuF+JOCg4Ifhoujg8OLoJ8++4Pvlt3lbfvYEszIB
            i39Pggc2N6yqKdw9MzIjWyaLqb9uPcvgvuSdWQdZZz5lphBt2HgkEhgQ4oiqLqrh
            T7UA
            =aOVV
            -----END PGP MESSAGE-----
        fp: 211FA1AE58F975F266A3E42E3CF239734CDBFD58
    encrypted_regex: (.*secret.*|.*password.*|.*users.*)
    version: 3.5.0
