---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    kbld.k14s.io/images: |
      - Metas:
        - Tag: 0.9.3-debian-10-r105
          Type: resolved
          URL: docker.io/bitnami/metallb-speaker:0.9.3-debian-10-r105
        URL: index.docker.io/bitnami/metallb-speaker@sha256:bf49e45d1937f026fa4595756c2d2f73318f0879b15f9b0901a412f566ac5466
  labels:
    app.kubernetes.io/component: speaker
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: metallb
    helm.sh/chart: metallb-0.1.18
  name: metallb-speaker
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: speaker
      app.kubernetes.io/instance: metallb
      app.kubernetes.io/name: metallb
  template:
    metadata:
      labels:
        app.kubernetes.io/component: speaker
        app.kubernetes.io/instance: metallb
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: metallb
        helm.sh/chart: metallb-0.1.18
    spec:
      containers:
      - args:
        - --port=7472
        - --config=metallb-config
        env:
        - name: METALLB_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: METALLB_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: METALLB_ML_BIND_ADDR
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: METALLB_ML_LABELS
          value: app.kubernetes.io/name=metallb,app.kubernetes.io/component=speaker
        - name: METALLB_ML_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: METALLB_ML_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secretkey
              name: metallb-memberlist
        envFrom: null
        image: index.docker.io/bitnami/metallb-speaker@sha256:bf49e45d1937f026fa4595756c2d2f73318f0879b15f9b0901a412f566ac5466
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: metallb-speaker
        ports:
        - containerPort: 7472
          name: metrics
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsUser: 0
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: metallb-speaker
      terminationGracePeriodSeconds: 2
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
