apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-controller
  labels:
    app.kubernetes.io/name: metallb
    helm.sh/chart: metallb-0.1.15
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: metallb
      app.kubernetes.io/instance: metallb
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metallb
        helm.sh/chart: metallb-0.1.15
        app.kubernetes.io/instance: metallb
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: metallb-controller
      terminationGracePeriodSeconds: 0
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: metallb-controller
        image: docker.io/bitnami/metallb-controller:0.9.3-debian-10-r85
        imagePullPolicy: IfNotPresent
        args:
        - --port=7472
        - --config=metallb-config
        ports:
        - name: metrics
          containerPort: 7472
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
        runAsNonRoot: true
