- hosts: site1
  gather_facts: no
  tasks:
      - name: Include site1 roles 
        include_role:
            name: "{{ item }}"
        loop:
            - metallb
            - traefik
            - bitwarden
            - ceph-csi-rbd
            - ceph-csi-cephfs
            - cert-manager
