- hosts: metallb
  gather_facts: no
  roles:
      - metallb
- hosts: traefik
  gather_facts: no
  roles:
      - traefik
- hosts: bitwarden
  gather_facts: no
  roles:
      - bitwarden
- hosts: ceph-csi-rbd
  gather_facts: no
  roles:
      - ceph-csi-rbd
