- hosts: metallb
  gather_facts: no
  roles:
      - metallb
- hosts: traefik
  gather_facts: no
  roles:
      - traefik
- hosts: bitwarden
  gather_facts: no
  roles:
      - bitwarden
- hosts: ceph-csi-rbd
  gather_facts: no
  roles:
      - ceph-csi-rbd
- hosts: ceph-csi-cephfs
  gather_facts: no
  roles:
      - ceph-csi-cephfs
- hosts: cert-manager
  gather_facts: no
  roles:
      - cert-manager
