- hosts: site1
  gather_facts: no
  tasks:
    - name: Include site1 roles
      include_role:
          name: "{{ item }}"
          public: no
      loop:
          - metallb
          - traefik
          - ceph-csi-rbd
          - acme-dns
          - cert-manager
          - bitwarden
- hosts: site2
  gather_facts: no
  tasks:
    - name: Include site2 roles
      include_role:
          name: "{{ item }}"
          public: no
      loop:
          - metallb
          - traefik
          - ceph-csi-rbd
          - acme-dns
          - cert-manager
          - bitwarden
