---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ceph-csi-cephfs
    chart: ceph-csi-cephfs-2.1.2-canary
    component: nodeplugin
    heritage: Helm
    release: ceph-csi-cephfs
  name: ceph-csi-cephfs-nodeplugin
  namespace: ceph-csi-cephfs
