---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ceph-csi-cephfs
    chart: ceph-csi-cephfs-2.1.2-canary
    component: provisioner
    heritage: Helm
    release: ceph-csi-cephfs
  name: ceph-csi-cephfs-provisioner-http-metrics
  namespace: ceph-csi-cephfs
spec:
  ports:
  - name: http-metrics
    port: 8080
    targetPort: 8081
  selector:
    app: ceph-csi-cephfs
    component: provisioner
    release: ceph-csi-cephfs
  type: ClusterIP
