apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cephfs-root
  annotations: {}
provisioner: cephfs.csi.ceph.com
parameters:
  clusterID: c28884d0-cab2-11ea-a70f-00163ed49eca
  fsName: ceph-fs
  csi.storage.k8s.io/provisioner-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ceph-csi-cephfs
  csi.storage.k8s.io/controller-expand-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: ceph-csi-cephfs
  csi.storage.k8s.io/node-stage-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/node-stage-secret-namespace: ceph-csi-cephfs
  mounter: kernel
  provisionVolume: "false"
  rootPath: /
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
mountOptions:
- debug
