apiVersion: v1
kind: Secret
metadata:
    name: authsecret
    namespace: traefik
data:
    users: ENC[AES256_GCM,data:OLYbFUpwS9PRqfqCm52jb4HGK6ulD4qp5NGI3yeSQCCxc1unDjOxRtUVRA21pFDQS2OmWX682qxBVBHPrPxGdg==,iv:RiatxXjE1ZXTCbAftygtR4rn6b4pFdCl6WmcM6SB5Jc=,tag:b4RfLvH9YXy22Ci7tzGcnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-07-29T04:03:07Z'
    mac: ENC[AES256_GCM,data:e8mnfjlybpofjl2rVg4Nu9dMnncHm4CKBx8QcSCn78iRnaxcy66JUjOcB+yY1o9z3KfJdMdnGVYtF17KG3WoL4nmRb7MaUJ/gu0PI40MS88zv220oT6H3DZwsAb8y6kQ9nf5z/HhOgCJGfMgN9bkTFO+7xPj1DCDfXLdxBsrjCM=,iv:TDYlsl7hGB2L4dA+9oJrBuy5hM9Aq/TGEmc/aPSkT+k=,tag:chqxm74wrKwoATqdsj3sxQ==,type:str]
    pgp:
    -   created_at: '2020-07-29T04:03:07Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA8+hman75/nUARAAHyH2CUOjFMIXoVL0XOJ1DU61t3RpKNa/DuEmGGjY33s9
            zOJzleH5KyhEIJl23nFciWe7UQ81tmPfW6Vgsa6k6+StkggT7Sqkvt4jXC+aDmV0
            USJ9Nn134vNWRUBNzqq5MlXCmBllDyfPwcPbdWxya7yKWOCCwCV987ZAHZwMyBwK
            rljW2ElvBw6trBHV/5yPXL6wIxf+jpM3RV68zc46LMsmI2ybOKEhD2ODNLZZnntN
            f2jo+d+5IBqza4D51N5TFALgKdkItUMylXkHrMD+/1y79tbZIcuhDvQd/XY6p4Cy
            HDIeOgJF7O8ZvqeC6RWlJKWZcnHy7tx+piDBQOhYJMmQ424pR2EHZUTx5z8L+9nL
            d2SpFcHEWTsHHEewatpOaKsMgJKzG/MDsZCescQty6fhD270xB2hZohlHctd5Kcn
            5Dv4XtTLI6zpfbg+T6bYJdPYt8XuCETGwlALMGrwp3epzTmBXtKsIJkpQ2rvqqrB
            0KmuRQndjYJa8cdyZkQbb5k9iGsVgC+B9xxpuKeZgdJt9bgaWL3PVFr2sBOuvm7T
            ltej6WLnXGfqmNs93wai8MUdo2SovN4BOjMJUmYI3HxZDCAmKlrwBdeODs4yXVXg
            HBWiBpXqXoc+813bA8HMznNz+rVGan38Q3H1+P66zYdZGd2wxri69OHeYADXVIvS
            4AHkqRWnsX6X9aHmjtWz+dthP+H2dOAX4L3hbsDgZuKrRHox4InlsvB2uYzxkpli
            GO3iQUOMghLqhKPmAy2kCC5WP1efoxfgqOQDALyvY+HBYDeOIN+otiRq4kJRHH7h
            xNwA
            =w47n
            -----END PGP MESSAGE-----
        fp: 211FA1AE58F975F266A3E42E3CF239734CDBFD58
    encrypted_regex: (.*secret.*|.*password.*|.*user.*)
    version: 3.5.0
