apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: admin@traefik
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
    - dns01:
        cnameStrategy: Follow
        acmeDNS:
          host: http://dns.traefik
          accountSecretRef:
            name: acme-dns
            key: acmedns.json
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: admin@traefik
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production-account-key
    solvers:
    - dns01:
        cnameStrategy: Follow
        acmeDNS:
          host: http://dns.traefik
          accountSecretRef:
            name: acme-dns
            key: acmedns.json
