---
apiVersion: v1
data:
  config.json: '[{"clusterID":"c28884d0-cab2-11ea-a70f-00163ed49eca","monitors":["10.0.8.105","10.0.8.33","10.0.8.62"]}]'
kind: ConfigMap
metadata:
  labels:
    app: ceph-csi-rbd
    chart: ceph-csi-rbd-2.1.2-canary
    component: nodeplugin
    heritage: Helm
    release: ceph-csi-rbd
  name: ceph-csi-config-rbd
  namespace: ceph-csi-rbd
