---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    kbld.k14s.io/images: |
      - Metas:
        - Tag: v2.1.2
          Type: resolved
          URL: quay.io/cephcsi/cephcsi:v2.1.2
        URL: quay.io/cephcsi/cephcsi@sha256:a5d30fb10a7dfd6db4481a7fbd7513b2b2ea3b2084e6cbcc880036b095d4061e
      - Metas:
        - Tag: v2.1.2
          Type: resolved
          URL: quay.io/cephcsi/cephcsi:v2.1.2
        URL: quay.io/cephcsi/cephcsi@sha256:a5d30fb10a7dfd6db4481a7fbd7513b2b2ea3b2084e6cbcc880036b095d4061e
      - Metas:
        - Tag: v1.3.0
          Type: resolved
          URL: quay.io/k8scsi/csi-node-driver-registrar:v1.3.0
        URL: quay.io/k8scsi/csi-node-driver-registrar@sha256:9622c6a6dac7499a055a382930f4de82905a3c5735c0753f7094115c9c871309
  labels:
    app: ceph-csi-rbd
    chart: ceph-csi-rbd-2.1.2-canary
    component: nodeplugin
    heritage: Helm
    release: ceph-csi-rbd
  name: ceph-csi-rbd-nodeplugin
  namespace: ceph-csi-rbd
spec:
  selector:
    matchLabels:
      app: ceph-csi-rbd
      component: nodeplugin
      release: ceph-csi-rbd
  template:
    metadata:
      labels:
        app: ceph-csi-rbd
        chart: ceph-csi-rbd-2.1.2-canary
        component: nodeplugin
        heritage: Helm
        release: ceph-csi-rbd
    spec:
      containers:
      - args:
        - --v=5
        - --csi-address=/csi/csi.sock
        - --kubelet-registration-path=/var/snap/microk8s/common/var/lib/kubelet/plugins/rbd.csi.ceph.com/csi.sock
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: quay.io/k8scsi/csi-node-driver-registrar@sha256:9622c6a6dac7499a055a382930f4de82905a3c5735c0753f7094115c9c871309
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - rm -rf /registration/rbd.csi.ceph.com /registration/rbd.csi.ceph.com-reg.sock
        name: driver-registrar
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
        - mountPath: /registration
          name: registration-dir
      - args:
        - --nodeid=$(NODE_ID)
        - --type=rbd
        - --nodeserver=true
        - --pidlimit=-1
        - --endpoint=$(CSI_ENDPOINT)
        - --v=5
        - --drivername=$(DRIVER_NAME)
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DRIVER_NAME
          value: rbd.csi.ceph.com
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        image: quay.io/cephcsi/cephcsi@sha256:a5d30fb10a7dfd6db4481a7fbd7513b2b2ea3b2084e6cbcc880036b095d4061e
        imagePullPolicy: IfNotPresent
        name: csi-rbdplugin
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
        - mountPath: /dev
          name: host-dev
        - mountPath: /run/mount
          name: host-mount
        - mountPath: /sys
          name: host-sys
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /etc/ceph-csi-config/
          name: ceph-csi-config
        - mountPath: /etc/ceph-csi-encryption-kms-config/
          name: ceph-csi-encryption-kms-config
        - mountPath: /var/snap/microk8s/common/var/lib/kubelet/plugins
          mountPropagation: Bidirectional
          name: plugin-dir
        - mountPath: /var/snap/microk8s/common/var/lib/kubelet/pods
          mountPropagation: Bidirectional
          name: mountpoint-dir
        - mountPath: /tmp/csi/keys
          name: keys-tmp-dir
      - args:
        - --type=liveness
        - --endpoint=$(CSI_ENDPOINT)
        - --metricsport=8080
        - --metricspath=/metrics
        - --polltime=60s
        - --timeout=3s
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: quay.io/cephcsi/cephcsi@sha256:a5d30fb10a7dfd6db4481a7fbd7513b2b2ea3b2084e6cbcc880036b095d4061e
        imagePullPolicy: IfNotPresent
        name: liveness-prometheus
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: true
      serviceAccountName: ceph-csi-rbd-nodeplugin
      volumes:
      - hostPath:
          path: /var/snap/microk8s/common/var/lib/kubelet/plugins/rbd.csi.ceph.com
          type: DirectoryOrCreate
        name: socket-dir
      - hostPath:
          path: /var/snap/microk8s/common/var/lib/kubelet/plugins_registry
          type: Directory
        name: registration-dir
      - hostPath:
          path: /var/snap/microk8s/common/var/lib/kubelet/plugins
          type: Directory
        name: plugin-dir
      - hostPath:
          path: /var/snap/microk8s/common/var/lib/kubelet/pods
          type: DirectoryOrCreate
        name: mountpoint-dir
      - hostPath:
          path: /dev
        name: host-dev
      - hostPath:
          path: /run/mount
        name: host-mount
      - hostPath:
          path: /sys
        name: host-sys
      - hostPath:
          path: /lib/modules
        name: lib-modules
      - configMap:
          name: ceph-csi-config-rbd
        name: ceph-csi-config
      - configMap:
          name: ceph-csi-encryption-kms-config
        name: ceph-csi-encryption-kms-config
      - emptyDir:
          medium: Memory
        name: keys-tmp-dir
  updateStrategy:
    type: RollingUpdate
