---
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.rbd.csi.ceph.com/aggregate-to-ceph-csi-rbd-provisioner: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: ceph-csi-rbd
    chart: ceph-csi-rbd-2.1.2-canary
    component: provisioner
    heritage: Helm
    release: ceph-csi-rbd
  name: ceph-csi-rbd-provisioner
rules: []
