apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-backup-pv
  labels:
    app.kubernetes.io/name: bitwarden
    helm.sh/chart: bitwarden-0.1.1
    app.kubernetes.io/instance: bitwarden
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
