---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: bitwarden
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: bitwarden
    helm.sh/chart: bitwarden-0.1.1
  name: bitwarden-backup-pv
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5G
  storageClassName: cephfs-root
