---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
    kbld.k14s.io/images: |
      - Metas:
        - Tag: latest
          Type: resolved
          URL: skeen/bitwarden_rs_backup:latest
        URL: index.docker.io/skeen/bitwarden_rs_backup@sha256:941a470106cbf6ede1427f16f614e1d5ef5ae951dbcc930578ff71f6a7e1f2ff
  labels:
    app.kubernetes.io/instance: bitwarden
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: bitwarden
    helm.sh/chart: bitwarden-0.1.1
  name: bitwarden-database-backup
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - bitwarden
                topologyKey: kubernetes.io/hostname
          containers:
          - env:
            - name: SOURCE_DATABASE
              value: /bw-data/db.sqlite3
            - name: BACKUP_DATABASE
              value: /bw-backup/backup.sqlite3
            - name: TIMESTAMP_BACKUP
              value: "false"
            - name: TIMESTAMP_FILE
              value: /bw-backup/timestamp
            image: index.docker.io/skeen/bitwarden_rs_backup@sha256:941a470106cbf6ede1427f16f614e1d5ef5ae951dbcc930578ff71f6a7e1f2ff
            imagePullPolicy: Always
            name: bitwarden-database-backup
            resources: {}
            volumeMounts:
            - mountPath: /bw-data
              name: data-storage
            - mountPath: /bw-backup
              name: backup-storage
          restartPolicy: OnFailure
          volumes:
          - name: data-storage
            persistentVolumeClaim:
              claimName: bitwarden-pv
          - name: backup-storage
            persistentVolumeClaim:
              claimName: bitwarden-backup-pv
  schedule: '* 3 * * *'
