---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kbld.k14s.io/images: |
      - Metas:
        - Tag: latest
          Type: resolved
          URL: bitwardenrs/server:latest
        URL: index.docker.io/bitwardenrs/server@sha256:838c179d4bf189642897ca0b21adda55bbdbe685fc89a66d7d70f57791dc4384
  labels:
    app.kubernetes.io/instance: bitwarden
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: bitwarden
    helm.sh/chart: bitwarden-0.1.1
  name: bitwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: bitwarden
      app.kubernetes.io/name: bitwarden
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: bitwarden
        app.kubernetes.io/name: bitwarden
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: bitwarden-conf
        image: index.docker.io/bitwardenrs/server@sha256:838c179d4bf189642897ca0b21adda55bbdbe685fc89a66d7d70f57791dc4384
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: http
        name: bitwarden
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources: {}
        volumeMounts:
        - mountPath: /bw-data
          name: data-storage
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: bitwarden-pv
