apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitwarden
  labels:
    app.kubernetes.io/name: bitwarden
    helm.sh/chart: bitwarden-0.1.1
    app.kubernetes.io/instance: bitwarden
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bitwarden
      app.kubernetes.io/instance: bitwarden
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bitwarden
        app.kubernetes.io/instance: bitwarden
    spec:
      containers:
      - name: bitwarden
        image: bitwardenrs/server:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: bitwarden-conf
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        volumeMounts:
        - mountPath: /bw-data
          name: data-storage
        resources: {}
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: bitwarden-pv
