apiVersion: v1
kind: Service
metadata:
  name: bitwarden
  labels:
    app.kubernetes.io/name: bitwarden
    helm.sh/chart: bitwarden-0.1.1
    app.kubernetes.io/instance: bitwarden
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: null
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: bitwarden
    app.kubernetes.io/instance: bitwarden
