---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: bitwarden
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: bitwarden
    helm.sh/chart: bitwarden-0.1.1
  name: bitwarden
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: null
  selector:
    app.kubernetes.io/instance: bitwarden
    app.kubernetes.io/name: bitwarden
  type: ClusterIP
