apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: metallb-config
  name: metallb-config
  namespace: metallb
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.0.9.20-10.0.9.29
