apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: metallb-config
  name: metallb-config
  namespace: metallb-site2
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.10.10.1-10.10.10.10
