---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kbld.k14s.io/images: |
      - Metas:
        - Tag: 0.9.3-debian-10-r97
          Type: resolved
          URL: docker.io/bitnami/metallb-controller:0.9.3-debian-10-r97
        URL: index.docker.io/bitnami/metallb-controller@sha256:c3bd7e05afa835afbc10ed798c8faf05e5962952d571f0050613941223e7cd2d
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: metallb
    helm.sh/chart: metallb-0.1.17
  name: metallb-controller
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: metallb
      app.kubernetes.io/name: metallb
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/instance: metallb
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: metallb
        helm.sh/chart: metallb-0.1.17
    spec:
      containers:
      - args:
        - --port=7472
        - --config=metallb-config
        image: index.docker.io/bitnami/metallb-controller@sha256:c3bd7e05afa835afbc10ed798c8faf05e5962952d571f0050613941223e7cd2d
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: metallb-controller
        ports:
        - containerPort: 7472
          name: metrics
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
      serviceAccountName: metallb-controller
      terminationGracePeriodSeconds: 0
