apiVersion: v1
kind: ServiceAccount
metadata:
  name: metallb-controller
  labels:
    app.kubernetes.io/name: metallb
    helm.sh/chart: metallb-0.1.15
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/managed-by: Helm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metallb-speaker
  labels:
    app.kubernetes.io/name: metallb
    helm.sh/chart: metallb-0.1.15
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/managed-by: Helm
