apiVersion: v1
kind: Secret
metadata:
    name: csi-cephfs-secret
    namespace: ceph-csi-cephfs
stringData:
    userID: ENC[AES256_GCM,data:NVII91I=,iv:+QLo51vRVm6T6avb6cJ4YMZvFza7clWkPEp38N+X9ZA=,tag:hxCCjaz2U+TW8+6IUQrt5w==,type:str]
    userKey: ENC[AES256_GCM,data:qtCJzoii3kLtnTEyiFpprCgs7bcGMXWwaXKWS3wMpQr+ylL7G8/JmA==,iv:fQ0+FtAG0ei1B9RKBNsteR4LAYcBS7N7IJ9VASt6MXs=,tag:3TmC+jrGzjyzQvOQyGa1VA==,type:str]
    adminID: admin
    adminKey: AQDE2xVfOiA9IxAAkAHRNrkvx6310BklqabzkA==
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-07-30T00:43:51Z'
    mac: ENC[AES256_GCM,data:3Ych8huvC5fULXTO/3vE+5825vPjKuAEzbBy4Ws3KBJBLQZkyIuZJCudWCYtJH8McAYhDEJ0VsQaBJzuE+/7laqIMc9opwSv+3Fjpd+azmqSXG5dHhiAxNU8vnsJ0NXMPhxxU5j7AREJ+OMM8VittYKq9ZNPNfvl//Aouo06E04=,iv:plYaIbTyUzqfchwL2KVlpJbsvAv6CaVM7P4rKkM3eOo=,tag:dfRsYxG8/RsCaqAZZKn/qw==,type:str]
    pgp:
    -   created_at: '2020-07-30T00:43:50Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA8+hman75/nUARAAbbDkhVGmLVRN4Qmfz9pjX2ClKTWPRmMQD87pYSO6HgA9
            IjX7qmDuCCZo+AAjnqSyAcoDSD8VnhrDdON/mPeyriYo3jmr8O0QQlGdMG2Qb0tX
            D0LiuhHWISO5lwnu2SFyjx3HwjJLEZfFRsh0qcZ0GGMy60x3wQR33PstlMXsxLqN
            d8sYAo5naXDDC0+EN7+vqA6DAMFWVF/QN2guQBrbcK9sQS7NEB1B4JeMGIRWakW0
            RAXnFaxDfrqmqJAMyo3zs6aRW41rt1fbJONhML4ezkMNu0Er8l+LBKlfRZUdA18C
            J2OYwok/gncB/mYlcIEWWhOo5EKcB/Ku8Sf+2ImKAz98rXbP8fJQxxnspL2/pcT+
            rLOfK5bBhfkFXmFpp2m/gobHeKqeOD3jtTPgoTGbsHkihsNaddL1BK1JX6MvJ38V
            PaIsJ4/uQ5Sq2gWmWQJEqB7YbU2Q/ZlVF4jM4QVeeI+C0h8R9i6DHqqSrt4ovUHs
            F5xq+DwzOpy1bUPAvQwt5L/3zI6Gz2WA1uRFgb4BkNhDm9r55pzHvIDJmWWBc+zr
            lSCd16sHFigjJZNPeOMVwOVZNQ6MUCtzqMEXV1hF+JM3LeOoUrkxkIjr3Yv/CAhy
            22y/FlX9hzwW4Nix59qtTnX8MPVQ8cJCDFBcLoPjUqHgfB8WQmn8OKIPuoBdFB/S
            4AHkdjE7TrqYf+4BgauJRSuW0+FVgeD+4MThqdPg4OKp3a6J4Fnl2WyXi7pj48Om
            urYZRO53KcP7WQQlpX31GYblpwjMI/3g8OSnvVM+bDMN19G67P0aM2QN4h/yDG3h
            KQQA
            =/quK
            -----END PGP MESSAGE-----
        fp: 211FA1AE58F975F266A3E42E3CF239734CDBFD58
    encrypted_regex: (.*secret.*|.*password.*|.*user.*)
    version: 3.5.0
