#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ def config():
address-pools:
  - name: default
    protocol: layer2
    addresses:
      #@ for address in data.values.metallb.addresses:
      - #@ address
      #@ end
#@ end
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: #@ data.values.metallb.config_name
  name: #@ data.values.metallb.config_name
  namespace: #@ data.values.metallb.namespace
data:
  config: #@ yaml.encode(config())
