apiVersion: v1
data:
    secretkey: ENC[AES256_GCM,data:P5WZ3fkvrOfA66/gHEELvLnHXUpP0/8dke+akEJKPlYW3y8RPlXJQ+vNmCPD7H3R/Hm0boD3SK+GhrgZ9skzWFDdiOc/mlD8mswjgMyd1TCkdAE1QgbvCjp6eK95PFgEaG4n91bF2KIviUwpadsAt4Lfx7TbQMeRZIvXjqwvw+fbXOMMNHywvMWs5fzhBARRLraq87zMWgFOnqi8BPIi7eBfAKB377EmSRgX0g==,iv:juHCcOX6E+kVv068QvFauvvNMckzEgjXa7C1Fb2QZhk=,tag:3v6iMmCXGSZAS83uMSUCmA==,type:str]
kind: Secret
metadata:
    name: metallb-memberlist
    labels:
        app.kubernetes.io/name: metallb
        app.kubernetes.io/instance: metallb
        app.kubernetes.io/component: speaker
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-07-04T14:14:40Z'
    mac: ENC[AES256_GCM,data:2nU3+9Lp5tH3KUmnzHcMjuds5lhEBZ8UaBK9PehCfT42hScuit0MWg9243Dll6mD/l0XtPY3Et7DxCDwK1LCyJSdyh5rUwKCFyLSQzHWHkDvtv6YfSdWHYXnSjGw0SkLW9ZfLHtKT8NcuHMruaqwYsq+M5jd9xzxaN8rrio16cw=,iv:VKCrtUQ0n7o81nPESPpJAs+0Hfft1Yo+wt4mJyYc8LM=,tag:9YZD3c1lpW6ieyWrFyZDIQ==,type:str]
    pgp:
    -   created_at: '2020-07-04T14:14:39Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA8+hman75/nUARAAeGzpAWOWZbBcgxqlX6rZJsihU2yjdiF51jp4yGU74gF3
            mrQjjbht4dKovaqX39bu/+MCJC6wQfE5OdN7bvk8xZ09iBJri/N3Csl0LeK9rxdT
            TjwhZdkAmvPW1zU5byPyklExgJkaC2/adUeUjUM/9qVsVEBpH5Qru05h7J1lCe7Q
            2zkDayMyD8b5XbIaAE3F6kh+MkW27QI8c+4yuOlFDIioZaYKBx1CKyEe1Obp/BT7
            2+aK6LUd7GjzTvg1TRqAVci1X19jrOdqKxGGwZWRqyMI9H2GpF7XuOrTBpwvnreE
            WVvlQ193TZEa+mSOYzxvKJoyZ7SbDX35Izw4AVYUnsoyi3Y6uKI1op5qOZotcxTM
            zYMf1AalIJce6KfczRgacj3httLAf35Y2G5wvIxgKOw/DP5op0wlB0PbMISF2QVi
            a6WasJFyVLHeBatzECXzFV0/X5k2ap0VB/+TCUY82fQIT9yjibyougMhKLCMGqAN
            eZ48jBcRoyV7jOgC7wU3O9xOXRshGA1GGqnak1xAY6ZEmsF0s1u1EKeSL+Yfigjx
            UN7Uprp/hAnijzu3MGPTxUfEeWlHip40o0NUfLYz0AclLANoXQ/A7sekK3+GwKKL
            Aem7WxMRtuETI4Vw6o603u85jrfv9Gk0ofbKef9HWzm2pGdp+hWjRmSivcIP4LvS
            4AHkBtYs3EAOCbA2pgqdlMie2eH/aOAz4C/hthfg/eI6VMx34GTlBOT7RU0+UX+v
            yIKfxrSqXMe/npZAtvJqVW9PSIB6NZfgmOQ1t7ps8D9/LI1TaGs/HHbm4i/WipTh
            qUwA
            =WRQf
            -----END PGP MESSAGE-----
        fp: 211FA1AE58F975F266A3E42E3CF239734CDBFD58
    encrypted_regex: (.*secret.*|.*password.*|.*users.*)
    version: 3.5.0
