apiVersion: v1
data:
    secretkey: ENC[AES256_GCM,data:+BJHSmCJQ6wRR0D9tozt7zE3k8OUsh4hK9C4f5w36v/jBankkaGNHC9yi19n17JtnSSURd+kSNP2KAi+zRBZkUR5/ZU1HB22x9UFz9Kz/jOi9S6tvCJQicANn4R12JpMnBdym2AKrWsz0b9jDdE7soTnjMkossYzpsdrOYebMHAhEbxYJl6B66BmZX8Wh8FmMQf44HaQpbLlcfBoed/KRMKoPHFIGLXD5r39VQ==,iv:N5SFhQ+ctPKIKjxWuNSB/41vEXLRO38M/DaXgwG8Fnk=,tag:6hteeuQCaL6f/Nnp6J0mqA==,type:str]
kind: Secret
metadata:
    name: metallb-memberlist
    labels:
        app.kubernetes.io/name: metallb
        app.kubernetes.io/instance: metallb
        app.kubernetes.io/component: speaker
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-07-04T15:54:09Z'
    mac: ENC[AES256_GCM,data:Z5nWIDgnpNS+L1BKDzp6h3cJV1Q/Lrm2R8zPDx+KvWV5DS+bc0coc1n9Kz4GvIYEg4UX27U9NeJpcuGzU7k8Knu/7LZT3KMFj88cy1WCUSQrJARSTYP7DUPys7vmBApJVgADh9FM/JRfdy/lgxg46qQEJiZiFKszzOqEVxxLnj4=,iv:ObuoNmSKWsoi1mO/d92jaw7g8p2IDVH354U+x1BqALw=,tag:lE7UqTUME35+pU7mHLroUw==,type:str]
    pgp:
    -   created_at: '2020-07-04T15:54:09Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA8+hman75/nUARAAJlAzp3L3gMsZsH4VdL+1cRcfBN4ELRdll62wLVg8TkQ5
            YdQjaXleLfMSnxWe5JgS4PZblPQbceyDQEuJiDDpUq1LLAA1cg13lqmXk2mw/H5O
            561m8hT43YmtMuLLPc4shsLzKhfpafXWaxEvpmbRicDoTEEQGmGok8wPKmADDlBh
            jbabMWjc7AZvLXAVnLFIamMwuS1JJosRZkkS8BXBZ+1Ot+HGanKH+YNuJPIYPaGe
            GS6jw+k/UhWCgB+2fHL2W5OmJ6Nd1No9zXA2urvEKyKkoZ1z+kfl32Kmpk9s+C3/
            8GoRpxt+Gb126v9McODH5ieXT/AZFQ4igHjfoIFzj7rVbsQnmVTHR8WR8fjyEpPF
            fW5qDx6k45Rg78V/nXoHVSNBMeDTEB4UzRLL3FAaJmsMVlwO6Sve86XnMuidclZI
            hTnyAiezrxBhCcE4bXxx5VX/O6f8CN/8OnqjoLu8jFVcOf1NxUfW4acF5o1SihKH
            6pXW1CQyoQ0hO7cXkK07QOoQzdTGBKGcmIzslszoO7yAoeHAL+yxkLtg0djK17RB
            mTzT8bTny/tOejIYGG5ICQTgQtXM6SYLLppWow2QXTBIjTIHEMRC48IbgYySZWps
            zoDQtn1+VdiHN2nYmIq7VGcnCnk3N5PLbU8ATwC+colX+6Wz+Pw4ymMhSOKRDPPS
            4AHkmnNyg+wesRQ5yNKSx4IcNOFc2eDY4DzhNyHgEuK3SCre4PvlL9Ko+iPiSJxT
            s13sO2jRGCqg+Xyu7ZZdAySm7r9lDkPgq+SmiYWwItdEsOpq1mGVxxRq4jHJVL7h
            LkYA
            =s3P1
            -----END PGP MESSAGE-----
        fp: 211FA1AE58F975F266A3E42E3CF239734CDBFD58
    encrypted_regex: (.*secret.*|.*password.*|.*users.*)
    version: 3.5.0
