apiVersion: v1
data:
    secretkey: ENC[AES256_GCM,data:0821prj6vYiJobv7oFzPy2LolHfAfd14rmv8yZ6ckJL6hDCkFzD7xBYBZTIrpF6zfCFYky8ICLYTkoLdlJeLiP14ghpXZiciQxb4b6j3kMs736DIiyne33RCpL538/jpFcKSLpb0lWlc6BCPT2NGcy6BM9rKrKYBR07JaqWyr/vlMTZiTKU7Xg0qbSnxMgiejPPepjVuaTzVeNwi1dJvxl9+Mdvj6QutvniJ0+hdJgDCMJGvt52xV1Y1nVZRMml1tzQp7Fg8JO+ak7vBd+cCSdDp1djxYve844SD294BWGcnA3DOSr2Vvt4+wD48j8hcvxZKzoxbkyKxtoQ/5RI45AnSNCbXgtAqGsnoC4E1juY+ZbD6U6v3p1ChjhcJo4QO5K6iOkTiQDNm1KneOlE0N7CQt8WztHJUjr2h46J245aOBImzJQNf0jMMVxukPcIftBEy1bEXj80=,iv:iqJYyhE3/EcT8hgvy0MLrhdt/1c8PmwbhO3l4bPsRYA=,tag:8wt/QhKC7SdfmsfjVyZqow==,type:str]
kind: Secret
metadata:
    name: metallb-memberlist
    labels:
        app.kubernetes.io/name: metallb
        app.kubernetes.io/instance: metallb
        app.kubernetes.io/component: speaker
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-06-26T00:24:40Z'
    mac: ENC[AES256_GCM,data:bpvwFL41otWDi71/S5jgM7EZLKoHABAxYYvLkZ6gNuwDXXc4vkHyKZ9RyZwolujPe2uJStLvclOHOUmP+TlTtTI/qWpTJdft7nDZpu11m3nvsS7mVjubVqCGkL+cs1rPSy0OP69w8AiFstWUbitT+KW4HqIfY1+NplvxJnQmQ/g=,iv:yOjpnYumzI42JNJZK/pk/b0AxaHEEaON/6UY9R+nkkU=,tag:GXsOtNXgF/tYAIlOeUdulw==,type:str]
    pgp:
    -   created_at: '2020-06-26T00:24:39Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA8+hman75/nUARAAja0/6QMA/Wuv/yVsfZR2cV4gB5bxt24KnLfEsxTwX7Jj
            0VS6bJbKfyJVtBy6KJ8CuHvxengCCRayh2T4INLtqC+LN/VYeybAhLtBUKyWg5RF
            mJUdATFl1ADibgIhiJ/sB3yyfqfQc9UhvC6Zb0Mb+OQHByQVvHU2Vzh0ATNmXO2a
            elBy9Z42E1lFxqrktI9Kqzv+MpmFWzleyRaiLSruykMgfNG43hsUkKRvwIEyONni
            ErkioDc03mpp53M8Opk1n+NB3/To5a+th09ZxbUfULUeyHyUkpcA6+fGunWU/GWT
            IP6td16JMRME6am7CAfVGMUMSS0znNH8KlJh93Pw9fqpgKN6aE6QsvNix21dVqBm
            HKCmLrV3Pzpmai7m8S18PAaudviVCo1K9yTCOQwH1TbV3A8NTCQpAgU44vSmfdbh
            yTzvv+neJVHgHvOlli/djer3t7Eyr6Le5536lfJdQmCE90+MAx0GgH30caM2NMUH
            JOLGmDs+nRCf/bccoy1lGXhegUecex0VOQXVTST93ny56Mm5j9JweSansZvJlxK6
            yeFfyC+j9gmsTW3RWhGnHNyynr4gMorSkLpu4uwOiLd/4Mi3olSstHynddzqWlqm
            QBSITHL5R++958NCXOauhdaucRV9bqVFXNnESX/+yXHkWFqHhYtZr2A9GV/Rt6XS
            4AHklUdatCkiMTEQ7aGdfgTbieFlAOCa4G7hSQPg7OKfPiEf4AblMMsJuiKVVxPq
            /X5H52SFeAOgeuBYu2EK55J3ucFQdQDgAOTwI+WplyUpIe3myWOE3DIQ4uBPIaLh
            KW4A
            =DwTU
            -----END PGP MESSAGE-----
        fp: 211FA1AE58F975F266A3E42E3CF239734CDBFD58
    encrypted_regex: .*secret.*
    version: 3.5.0
