apiVersion: v1
data:
    secretkey: ENC[AES256_GCM,data:UWZTaasAcAtswKvtLOfCY3Vdrl/q7ng7bsajusf9fGlPpJ+yCHAezqSq0biMibQu0Y8ZxagJiLlp9kKPcQPh8GYlcm2t6brpHLXsH0cde0TtST2WAQ==,iv:Vly2Nri0imwdZCLRhmJCSA2Hcvs3htlBQdNqYdH/GHI=,tag:pSEy9ar+AgNZ05zFqFQZLg==,type:str]
kind: Secret
metadata:
    name: metallb-memberlist
    labels:
        app.kubernetes.io/name: metallb
        app.kubernetes.io/instance: metallb
        app.kubernetes.io/component: speaker
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-07-03T22:42:16Z'
    mac: ENC[AES256_GCM,data:s/ayBTHoGaAY+ox0zAjJJAumwep8+X9HvTdBd4xWPskHJoh2O+S/Kg/0YR+VUJUKw5vyG0CpNXM+5JAnGXObA0LGG2ialb7jxhrOFCz47DYT37wqFZpwIOQpsyk0VJE8etSWMUqMxvHW/6AlhMhCQkIdbotyl+9VKTOgHUQD2aI=,iv:6TptzjO01lSt6ojTU4Pj7wtoahZB4zuZFQ2aIqV8sa4=,tag:HeCiCoM4k61bJoxE0xoYRw==,type:str]
    pgp:
    -   created_at: '2020-07-03T22:42:16Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA8+hman75/nUARAAs3xKApmIyGldsAhYlQ5/PhhjxY/S/1/pjs8flUa1q4Dx
            kvlkM+uMiZMvhi2rQGqSv1/gXaXPZ0mn9vxoIblkPlktYn5uaFZOD53GtUev0N9i
            6YBv8oDlMJVBkWBWqOkB17tSVRZFWZZR4BirNFVUGz+ooOOHhl0dssI1JvfWYpH/
            AFgcmS9Mqhy4fpRGbS4Ah4h5eI7jht5VRoUqBpg8P32fLD+24OVh0jGBiIXlSQrU
            DxoRTdTZkLYgMRjHsgp07vgKKdqDG5WzflgfUvXkvMq13ryHJzEyLHQrsWY557CA
            1asuhdIkaM1jmKwqbr3yPSumayFAXwa2RP4xeBzXsBWg0ce4qkvskio+0swx19IX
            KSOfAhvaCEIj1js8dZhlflWB9Zphn2pQ+029y/pg0nBBTw8WQCC26elt5f8EIc9g
            N6vSfrXvByjC7G6wzIhIdxzx6fmsSzCpGWgLNXr+SOdbwtZRBLgbGXyk9bVfm9fE
            FJhgLk6GyweRhSzZjraxgj2ANjbg+7Ex9qOobYet1AYyzMFr8wainMrfi6eoo3SK
            FtZ6KlC9q35PKq0qBxy/0mgapgBj3BN4/E51Q7x2JC1YhLqjCiOn4zFMB4itLhuj
            0zYrjl8UrmTo7fYOhzmWuKd2wpIUq0TPoyaFqDA1uLy5rj2MF43bRmFJdmTNAe3S
            4AHkQl7b/63YVoRZdAzn1VArI+FYhOCY4InhFBrgN+I21YNx4MPlyYhBW5lEV9Fd
            ei+Kw24LsmRGqv7sw5+cncJi/CI03nngA+RrKXeMGjcyfmaPAYnvt3GC4p+hAAXh
            9HcA
            =fdgI
            -----END PGP MESSAGE-----
        fp: 211FA1AE58F975F266A3E42E3CF239734CDBFD58
    encrypted_regex: (.*secret.*|.*password.*|.*users.*)
    version: 3.5.0
