apiVersion: v1
data:
    secretkey: ENC[AES256_GCM,data:IAm6GsFpk5azFT37T/NXydWXXr6NWJw7tcQixmC4/Qog4DH8vljL/GsNhGmaTbYOPEes44TRbpSHQ7ib6Zrrn4jP+FFG8ugy8DQSPT0tppDo0vMPEFvImUq3YXBYTfVOlLk9f/Qwi+Cgp6pjfejyZhgE54o=,iv:GfAZaauD76kxroDgRRQ3kT1c4hIxMl+TGjSRbIhNQcU=,tag:gN6m2zlVPwTwP/PAT0SrTw==,type:str]
kind: Secret
metadata:
    name: metallb-memberlist
    labels:
        app.kubernetes.io/name: metallb
        app.kubernetes.io/instance: metallb
        app.kubernetes.io/component: speaker
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-07-29T04:02:51Z'
    mac: ENC[AES256_GCM,data:hoKgxx8vp/gMsKENCaRkhsqRVpYpINMZ4DhEnYhWODpbvkd7IGBL9AdaV3048ykJofWAa+c/+Zm8LyMHkokqy2NeKUdhFIl/G53Bh26FeD4r7YRzKQkJ6FQFAQFP96UCJ/69BYs2r6gqtW2IB2xr+Tw9ynxxBI9kTKipBYoe6I8=,iv:5otI7kVKGN6qrRmIsc73SZMQgewGAiIDM8/0j8gLK/s=,tag:StM4Utbk5oPIQyKeZfLahw==,type:str]
    pgp:
    -   created_at: '2020-07-29T04:02:50Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA8+hman75/nUARAAcDab1i4GKKB/uQBn6ukskAlM3IAaOeQxyt00IHmYBdQd
            b5x6vjudxLbAvs4OlXn+YuOaPgt5TZxB7u0e9u5/XK2iJPnfIKGHSgaHCi3IxOLR
            5QKksOX4igfe6HV0h8otzAqYSylBdx6qEML+1pNPztogEgeAxiNcbiPOSu818Vyz
            H6F4a4P6hn9WA45HJu+6HQgZUz9kCXP1qWcIrD7UoZtTiiQ0dOIx8lNsOTPSxnUy
            tlN4WjJhnwznhHAtBP/1Ce4HU1drx+LTEYFrUdU9/qMvqOnQN7xKrAwB3JJl4Ywi
            aHBOFlBcama01sb7FrmmToOA/6YNIB5O2q/ojhWLIQ+X3BygeVs+iRHjvKgz3Hvm
            77vrEEct21qED/rq5atHQNERGBka3KODV8cvLKiYYbcOET2y0mDZJGXN8T+O8S2i
            cyJ3oIUmjitjIFFU1Nn7Z0BlOoheZEm9PqJ/04nKfYdrwPV5F3PEbhhp2leJGoVa
            lQ/nPwcgtBwGLSP5PdRLQSVb/AX+MCAbflMjYtJUeAF9fPMjWht5Ce/fovrsYKGz
            ALS+OOMZPF+2NzVJ0A/Scez03iEvxzjezqQZs+t0C/HcVDrf9uvyR3kyESBADx7H
            vyzCUJcEC4387ATe/akuKKcLv11sxg9bPcIgu6brR2BZ7/cvee0+vEoVArAWFg7S
            4AHkOt0Fv1+S7yxWuYuZtgbuBuECruCg4MThBBLgnuJZBt094JnlNr9FRWhQMD8S
            xyHicc/DvtNE4JDsrC5vX0dIG1SnoCXg1uSo/HPxZ5BvnRX1jsBEhQ354tN1rfzh
            0QkA
            =x7eA
            -----END PGP MESSAGE-----
        fp: 211FA1AE58F975F266A3E42E3CF239734CDBFD58
    encrypted_regex: (.*secret.*|.*password.*|.*user.*)
    version: 3.5.0
