apiVersion: v1
data:
    secretkey: ENC[AES256_GCM,data:ziJnV5XpICr5H0vg9fqAv3lygkm7QvPDGXUE/Q9zoi6PQY4i+kaeIWHxItEyB3Di2rNslCrHHSY2OK2dApCBCqpwtfGQ8WaKLXm4zo/3rZ+Y9NxqphBAk9tSgCdWLdoQ0zOazrI881169jFH5DgKCAWS5bJFJq8Xo9hiTWXvBZ+ZlOVeBVJnVxU0K9quNRf2T470ePNDvTwPKbNsnX1q9sWwiDZLJSpKs3+Bgw==,iv:hHgEJWzwg5mQS9mFWX996acdm/LXRKNIFxycq1Utn4M=,tag:D41ObsmUpHfbFScIRpZ3tQ==,type:str]
kind: Secret
metadata:
    name: metallb-memberlist
    labels:
        app.kubernetes.io/name: metallb
        app.kubernetes.io/instance: metallb
        app.kubernetes.io/component: speaker
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-07-17T21:10:45Z'
    mac: ENC[AES256_GCM,data:2areIWSeMEF6g7YMrGdg7ZYEzUdLxlPxTdUMAIDPXPzxuG49ygR2EemEat9FRV1oWFXUINiYh6+RnsuBw4QmTKgqPX2uiLzk5tj8GLbl7J9g0A2rD3rwICSBxaEKvUxAspfKd8/AmoycLxa0E8cF2pnD1+alzbnG0QwfDrrYAB0=,iv:g7fkY9dz/qvdhTa7EBWxvSYeHJbiPqWQBy8RhBZSWMI=,tag:2PDWlX1+n7dfnf5kSRyl8A==,type:str]
    pgp:
    -   created_at: '2020-07-17T21:10:44Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA8+hman75/nUARAAnYyjmLawY7T+v4Md4HKchXD/ofBqe7w/DLZR4JR/bvNj
            /3ezFiGJBFrttpfYJdaO83+MxTkL/+Y4OUwzZgR1RMS5GZX956xBsrnRr1SN3f4c
            a03JSayMBsI2ysyG6gf6aiKWXzjr6gPSfFUq0j5yPXXD6EENvSAhknX70Fj4Bb/m
            5zmoUgdKe+WtSPhUJJtXv+sroMKw7z3AJbKKTu01uDrJAk2xg1zQ8xjXjC+Xumlb
            4ECdxAHi0eyD2A+ABt4aE0++SKGAe+cucQlLjNVMAJpDdOVZQKzbpAP2r93FfhM9
            HmciaznFMzbHKkj08JpmcoKL1JxRcUbx68dn5WJUzt+UZXO9jBoIuQfk9Kocl3LB
            dyCbwyd33GlGiqY3VS3U/v82NRO/gzhPNyVcp0l1qG1Nh8GKERakq66xWVBt52hj
            TlVYOfCx2VV+DRWwa/6QQVRYI8a3/Zl5+4JeZYoZS7E+aG6uV5YGsH3kRHm8U6eH
            jjpkytnLJbMoXDLvrk6J1Wj3zDGfcuTQ+3ZV12EU8HhX/W3OvlSL+Paxp356WZ3w
            tFROOkurcggcyUUNAw3Pgba9ynwOBVrpsCSXFRE/LFdlSugj1vOB2MCEEIOn+v8l
            sx2oAydFQ4tAaVj0pkDjO2KLFW9/MLhi/CSZGsj8wTnbRcm+SsZ82rw49TF/OnrS
            4AHkpPkAXNgKB51qqAxGvAuUheHu1uAV4DDhkwTgf+I3eKfj4FzlQn5RIeFBKclO
            +FwkjIFwq4LAd19b6DeAmIrcxsvcq3TgtuQFvhqgpXOVu8vrCTIGG0+O4q0RpjPh
            iyUA
            =HeaT
            -----END PGP MESSAGE-----
        fp: 211FA1AE58F975F266A3E42E3CF239734CDBFD58
    encrypted_regex: (.*secret.*|.*password.*|.*users.*)
    version: 3.5.0
