apiVersion: v1
data:
    secretkey: ENC[AES256_GCM,data:Eh5OMNzEIrwajGFe5RFq4ixtBUtMBhtemOkYvXuVErHtvcAvQPJMERXs5m0eYZguMP3nI3TgNTdmywtr3+V8j8+FVT+d9jROSD8Ead28mTtqhILNhSUDlOr5SSf5EfdGRxCLBm6pYBXWd1om4PQ9nCnQJx6C/qntd5PCDLL97wDXAqYc7Dkvx+SWvKCOFEteHHblgLE4RAxc5PgvdNN9h/nHLF+cqCxQ3vmWJBx+2g+gdbDsIJW/lCg+3hJtBDCp4izYR+1Lm+oOY8EO6pPTM+kIWE0ejP8UWi0wu40wZ/0oiZLldyWTIUv8vUBiWrqajRGJorrE85+uAkIMF1xF2UefAQLhf6VZqfEhFcceXneoAzxDuH1GYX0ul+QgXSfaLjjE4hwgSgASU8LUcVn5EAiSma3mOAShjImSNENp0aea89pHxy1szAQZKb99i9Wuzv+PJJIvNT4=,iv:HKUVPx2BjIG2CZDYqFfZMCLHtIKFD0fBajgfN7tBfxE=,tag:3XTHdu4hxPXsMNffsYkssw==,type:str]
kind: Secret
metadata:
    name: metallb-memberlist
    labels:
        app.kubernetes.io/name: metallb
        app.kubernetes.io/instance: metallb
        app.kubernetes.io/component: speaker
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-06-25T15:59:48Z'
    mac: ENC[AES256_GCM,data:XzyMUsb7v3bDqh79MDv6G5yXI1JQ9dZHKL5ZQKok8QobtdQjh2TnMvjP8F6p/ThThwpWBA/ddv7BggMHVZi18rX1Y0GeM4h8K7jeHF2ZggupUqn0V5kLvgxzO1u3cKBUEcsL5xQZoAL0NdS9FcWL8fL6LrLSZyRmU+MuonV1VcU=,iv:5ppeUTCZB9K/9IDsVepBRroQR9gZHr9OVmwB9dFvGM0=,tag:F+LoI4JSttxFylZuuUvDkA==,type:str]
    pgp:
    -   created_at: '2020-06-25T15:59:48Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA8+hman75/nUARAAk6TCtDkFRfXv2cB3kzzJGYWi6vAT87rPPSQJq0lxd7ak
            6JKYQgHnjg+yrnVt4iyphUk4VZzOCZKJPWsltGG+0hcOBHcowF0AMj1qz27c2xMv
            oQv53ApESvXiXioaYuZa+iw2HBQgmlj0RRBxhO0C3ovlKdnm1oBg9LasTVQ/InF8
            aJCif2sKsWVVfg5F1J6suYBN9FBuRbZ3o6jpPFMcnp6rw6k7p3NwXJdoJ6Vx9W9+
            gRD/GRzVb3RWrTgfoeNbR0Xo1/thBG7XUAm0Nefo0N07Y4JYlTbUlasL1bqnoqWK
            Vmga3Efa1zbz6QicO4R9tK0AcosP1ysT+vsRYDjRdZE/yz4MGSITJK+YxiUzyPSA
            v4g/2YhNOF3u+Wsxo4bDlOmfVceDoTSe8xhdGDgfk81wkdrK7XSXeuRlXTDaAUCe
            Fu2KupIT5bJsNQv7U4EI5OM5dFg4XuMbAiRX/pD1GJ4ErP+tBbHqU8Uo5splAZ7p
            KhJymZTnj77p7EVzVIO5XrRl5cry34OQD5b78otPatNzfzhKldvYpi0BvmsYWDm/
            tULYX+ppmI1mQUbqP0dZLTdI+aqCXHHvwUJT898QqBGQHd8ZYkO/v0qjl2G/KC/x
            taJNkd84Ioeo2VR6TnjUaaa4lNooIs7FbXF79oZqWKrTNZe91/BOC1NbfcFLH0XS
            4AHkRqdjC9WV1FkEttQyYs2hhuGcHuDu4DzhyUbgL+JQp0t04Njl03QtiYNADjo2
            6HeD2pZ6qLB46GLiC4Yj3pCnG06XppvgtuSwr1+IB+L4NvSSpsIZwbGu4krMbSTh
            2g0A
            =Y55z
            -----END PGP MESSAGE-----
        fp: 211FA1AE58F975F266A3E42E3CF239734CDBFD58
    encrypted_regex: .*secret.*
    version: 3.5.0
