apiVersion: ENC[AES256_GCM,data:tM4=,iv:n6OXz2Hp5duRPBfBsn9KQDsd9oy4Ov/iP5O6+UoJbaA=,tag:IVse5E8fXA4gu5JteyCHCQ==,type:str]
data:
    secretkey: ENC[AES256_GCM,data:h0R87IbDXWfD909IuwkOarb7V7RkAl/QLXgRmyLFmm6gsufAH9XCdJAMFpwlA1Wdq/jGo0ui/LJ7H6Wp+eGDEZHOjsbKOuBQRFQHa8H6Jc+WN8SIrDYtBi3YtTB+poWjy2W2qholQWsxBlk0TpDnAd2oB50=,iv:POkuENRPZaNiilwr23iiZXWKTy6LqSxeumJGJnx++S0=,tag:0lwcQdNFyZCAOLDOQvbR0g==,type:str]
kind: ENC[AES256_GCM,data:T35ZI90y,iv:PN2Hd6L6v/C6xEbGt7mX6PG9wK+8FviJyY//2PnLjXo=,tag:WAS6bQ8hNRd7faAJnG2qcw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ozzpBmdIgc0tqH+vmw8nvmlI,iv:XG2yiZm75vfdp/4YtkuPqT6Z+GTRulniTSl9z5+c1d4=,tag:EW71nholYwaLlcUgdhmloQ==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:/FonLiOwMA==,iv:1qSAlKM2WGwceB9FV+Is82/gbD+HQ5FFyzSCjr0XHBc=,tag:pJqsczhcrEgWwQVCo4gGtQ==,type:str]
        app.kubernetes.io/instance: ENC[AES256_GCM,data:4KPq180Pbg==,iv:JES0mzjLq6dZS7OXofnabUcYDgLDFtjQoHiu3ACz8Z4=,tag:fXHcL3UcQHvUFcxo2v/TXg==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:l4zG8WqjJg==,iv:6GJk+SkGHUIhdEhIvTzU/GjBgAZ+xFUxj+UWxbhaPJk=,tag:28q5cO37tJBRNJtfY8DXlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-09-09T14:26:21Z'
    mac: ENC[AES256_GCM,data:CmDLi5FB/IJH9ymXgNyXwpqY3/1yXP2NTR9urbIhWW8nFAS7JKoHH0lHIvqYkzAY/UaLgRZRsCyUT1ux9kyW+WWB79gjpvP3jFLMX0RKFoCjU/aLqUqtU8b8L+uys0Ncdru+0W2Wh/A35oIRAQVp+hTIRKr/HlJCmXp5A7dCToQ=,iv:2G19AP/Dn01MixwB+QtMisCJIiXtQJVhjnIeQHK5u1E=,tag:7eUQ1XpYBSNUCuLoX3jVow==,type:str]
    pgp:
    -   created_at: '2020-09-09T14:26:21Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8+hman75/nUAQ//Xv6ZJdFGdV3Ky/vGOz1A2P5a8B30PE6LP6C24ZVgT0qJ
            ZOnMMfol7XicKr5plL8ua4LrZw1UHXz9w8rJeFtDyDyXrY4goobFhE0xvwIPwUpG
            HqTEfqgV7RchKIci/oULw6tKXA4HNHx3R/kzweyAYkkWO9xdc/Vt/vS9aP8VLZbb
            E32l5EwrYW3x+1pW+kBN82hrIlAzyUlpH0QeqvzvzVoHTufT38PRaYNWLXUwi9oO
            x0eG+56p/nUpr392etTXbenF/C/xHixEbJqUyzG8lv+Wk6iJNLpJj6uXZayEq573
            v/lCamemp+k+Phnn7Z8EQn3BXO1RQmYwJdJHVGqYXz5P3aQPEmWPwwQdIHa/lJba
            CqSGnGQU7Dr/z9BxzbzvjrngcoEUyK/Xt4j1tbSRF8iITYP7Wz7JwH5Q6mMQ3TW7
            qiG3HFPEAiuivuz9Uj3LFeg+q79MhSzYE2/aHxTHPuL75Cq7xhiRm+TI9RY26iKt
            G52x5i042Vmr4hPvWd6YHdV48VrQBpBJ+j5BsN0TR5lGro9+H7GmSPZ8gBvQ2Qh5
            gVTDgyG8sT4upBDXBelzXjzCnmFsnsBrkNr362dSEeylahNoNy7e46nnD837wUJt
            kCaA5eQNjYAkVPcYPnEtXJfMeGGlhPI9oocz3dRfyykk5dd3NWLyfK8mOrTylJDS
            XgHCa20Rt/GbdYewKsjJFDr4V1tonJm2/9RmJC5klBi9jqD8EZaxmDK1Irv7fjGF
            wMedRhxe0ykqm+BY3ZSNzQLZXd3I3DqiH3sJ9DYKIwdhfPsIzUPZud4BHIGVut4=
            =OVgi
            -----END PGP MESSAGE-----
        fp: 211FA1AE58F975F266A3E42E3CF239734CDBFD58
    unencrypted_suffix: _unencrypted
    version: 3.5.0
