kapp:
    namespace: kapp
metallb:
    namespace: metallb
    addresses:
    - 10.0.9.1-10.0.9.254
    secretkey: ENC[AES256_GCM,data:y7fXYYjO+vXuC/WCWD8oSIPuLdSNT74HPea503CMgOWetAZOdm0nhamis36f+LNCPYPOMRjTM9F/UanUFg68BcPvV+G8ImKNNgk8ozVl0d7todo/nBqNgoO1ZTf0ojPghJw0n0ikuWm/H0e19Rsy5srQ1SPCfH85Bu558RFzoV3cbCLL/5FkdTbge0pLF8dx7KRCLzP66asE8q0N3GPzhKqQbg7k9jxMeixtI8saIizy3uoswKJuwnbsrZBYqWw9Gm0jSQNORh82RnFdCQrNP8XRHK9PXd9Cfoh7QFAInrgUvrjShsbo47CebmUROBG4dAAcvxKrMINiSNM7Xiahy6PI3QFsr9BCaaiYN+q8zBdMbHE6LeWP5j4EivLEmLhLB58txbI/eo69SKHr71DUinVA6loTI1M7e+8RKug0SpOvjzxWZpBhEMd2GjkAJR8AxhSVIvh3QRU=,iv:q1czSn4+s/txLgHxOBi/hLwKgZqAuFwPR/sQmCN9AHA=,tag:Pz622k+NArxtjqawtdV1dA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-06-25T15:12:14Z'
    mac: ENC[AES256_GCM,data:0JJnM3V+SDN6Y+TyjH5wbxnHrMCJYeb+v/c4AZBFeSoOgrr8gk9+Dn5hLGt3qar9nRAS2k1Lc4F5EZqaksU8hW0LeinWPMvQmu0RPw0wYTEtoKPtvKK1qrZncSC8xzfEgSndJlB+z5Lq4SqIimPpPV3u7K9KuUci6BkRDL++/SI=,iv:N+DFl21bGtv0D5AIZAt8BoDdAD8Xbk9TiekE61Qv6u0=,tag:HrNmtwPJhrJjRllrp4EVFQ==,type:str]
    pgp:
    -   created_at: '2020-06-24T17:19:58Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA8+hman75/nUARAAheXMtq6KVNalZupzrwTd7FcZ4vHAs0TPgSKCAK6I9C8j
            R0if1t/dqFwI1x5WjH5MWUOCR1LmsO9eVCfgb0armbuvRNgBOHlRYdSO+12SB93U
            jkCJKmFRG+s2AMVZPBuR62s05bovDSKY+6Vx/gT5mjMasEoiG2Ev0T8jGom4Kz0Z
            9MY0rQ7r+j6cn6oyMk+0mZfd0g8kRZHKPlyhsw6Spesj2V4EPuNbo/uO1C80/zRa
            /2LqpzIG7x7hVmrUaY6Wjq1qa3E0dA9ctwOOOz5R2AikGJ/s4amfzRp2lb5VxRGx
            i/iNvHKFPW9NywusyxO1j+Te4KbEplLeicUGhijqsX0F+KCnfdWEvoKpl2KiVOTg
            HDF0mBHPFwL7wL0Y5nxIMj5bxEdFySXdOiDV1dsXaQQq7Rz+7Doqp0uYSlgEp6mO
            hx1Jdpu5tp/1rxeLx5N6zCicF07iPQ/T8TNvWpeHbZVewWUBTril2ZSD0gVn4Zer
            PfJnq8VBZOWjuQcHAxVH0ItqSltzh/jRp7rMc4HxOLka7t5BUPfOfgf6RXbxJU6H
            5JBHti4Q0YLfvE+R6bicwK7WsS5CbQl3UTqfpvcSUK807Ql7LPcLnQV3gQr+OEbE
            tKKbMQ1CP3f6Guohz8JyLDr5I9Pcvwqz09MWigFptWZJN8oOEcRfqBqWGCRO8AjS
            4AHkzneNQmwGBUM+XoXu+kNDGOFkj+A44E3h8IDgIuKFvjiq4HjluXBFnLM2MkFd
            mNcvzVyk9RxxJl2uFEKZ2onFqhd1dOPg5uSygE5BX9LNG1eaca5g+pVc4jjT6Gfh
            MjsA
            =gyxu
            -----END PGP MESSAGE-----
        fp: 211FA1AE58F975F266A3E42E3CF239734CDBFD58
    encrypted_regex: .*secret.*
    version: 3.5.0
