kapp:
    namespace: ENC[AES256_GCM,data:7Nz1Sw==,iv:qMIoQpMPKPkyZSh2gkkULlLJLNrWOAdr4m+uOXFteh4=,tag:k0GPNj5sU5pnZLgD1A4Bvg==,type:str]
metallb:
    addresses:
    - ENC[AES256_GCM,data:BHLA+TrW3vwLgG+3gCirSuYf,iv:w4gkAG/3TqMfPrK5SW6QqmSzlXM5vydE2K8rpKg08lU=,tag:8IbOtRUWTZBlgDYygbkJww==,type:str]
    secretkey: ENC[AES256_GCM,data:bjjqG6FZY7a+9wLPYXRzhLvxo4IOQij3VsS1fvE88LLrb3c/TbQ9vO+Uyc7mvkgC47WFA9BO9P9JeXFXAZgTGrxbPCE51zK7BjbjduWfEVm6KBt5L7Le5G10dWp4tl5TErK+6CMgP7tI5H1tXZCxr6Uh0fY=,iv:GcilrbW/ImQIDPxB7jrgZEidz5puY2vqETH1Buyk1rA=,tag:7DyE2lHYq0p/T0uhdMNyrg==,type:str]
traefik:
    dashboard:
        hostname: ENC[AES256_GCM,data:Rl4NfwbaVuVroTa2PuxbOCY=,iv:ufBW/hRruxja6LZ4NDMvUmMYBHty2c427m8YJhBCVW0=,tag:ADcKEjCEoNz0TshlqjnERg==,type:str]
        users: ENC[AES256_GCM,data:jksog+pmxydQ1yr7K2tlOkNHC6PjGpeYcTuBDeCSWdsBo2cRGv767eeKLEzld665HcAVZv7tSz98nN1vtk+CoQ==,iv:DhzpMExntzDCdzGj10+q/hVVNMTWl2nyC7+Zil3KHb8=,tag:xlNjWJZd6hRfwl9s9p768w==,type:str]
    ingress_routes:
    -   name: ENC[AES256_GCM,data:KhyLLmztHrn9,iv:NnhVeHCkY2Hkot38iFSN8BZzjToo9Z/m98D9ElxA8h0=,tag:W/mEXhStnqCabGyGXmkGqQ==,type:str]
        uri: ENC[AES256_GCM,data:2CrViRg/nHaeRKSU5+Y6keE=,iv:d+kzbHWjn6Gv1/uUVrpPOpVXDeWhGWI8w89PyhWnOHc=,tag:giazw03SfXxvRIZZw5dyiQ==,type:str]
        namespace: ENC[AES256_GCM,data:joKB7bn6++UT,iv:jMkz9AqmUVR8JZMC6uccalMPTdX99/6SrR+UGBxOPQg=,tag:D7wzLvh8yAa9XqDT7ONBmw==,type:str]
        service_name: ENC[AES256_GCM,data:nX/FiD3hrcuW,iv:sFUuQMPOeAh+1uhmWT8lznN1qjBK35t4CjqILpa4xds=,tag:zGoiViemzVQHtzk4rob9ag==,type:str]
        service_port: ENC[AES256_GCM,data:l+8=,iv:c+4CIsoKtWM57hyCGQEpAcnlt4dQ8hj3qyg4iJlFU8c=,tag:/JUNbinVca+WN7QXOQraXQ==,type:int]
        insecure: ENC[AES256_GCM,data:7rFh0i8=,iv:yaLwda+xecGBTmg3a/B/VlO0ZY0hPRuhUpXcw1tvdCw=,tag:1YvZ4ilbucBSqwXm/oBcYA==,type:bool]
    -   name: ENC[AES256_GCM,data:d7VE005pXA==,iv:CzHiIofigP17SDFiberPUtCI4MZllQv5sNMj0hD7Y+s=,tag:i0LloVylXkm51pHFpPrcVQ==,type:str]
        uri: ENC[AES256_GCM,data:iRakWsdYVXevIBz4,iv:YVl+4oNicUHViV0Rgn8q8qtRVJPIoAZhZNEQOrqnsp0=,tag:ly161YOqxCoUO/NkCDh87A==,type:str]
        namespace: ENC[AES256_GCM,data:EEJXvqrURwY=,iv:lKiOv4Jjq30aK1BnecyQSQzpoiZzT6upG8t0c6pCGS8=,tag:wGs4ui9vgusdAKMz2+X4Mw==,type:str]
        service_name: ENC[AES256_GCM,data:eJdECuT6qA==,iv:JmqQlyjPqOloFtdkleMny0KTOoFY5H71KXnMbbY52sk=,tag:hgun2dbeRZrR+BZawPOSUw==,type:str]
        service_port: ENC[AES256_GCM,data:5/E=,iv:FReHzh5RiqlUvirjSnOr094oGCKTkPWs6cl2tzhrKl8=,tag:aFB+lWbQ6DAciYGfOdcTYA==,type:int]
        insecure: ENC[AES256_GCM,data:uZobIA==,iv:Ux/gQ8PDIyPXGtw7McZq9LR57vzeyUT+/mDGApl6+ZM=,tag:svtTdvDul29lpIKMjl9O5g==,type:bool]
    ingress_routes_udp:
    -   name: ENC[AES256_GCM,data:Klyu5ZUIbA==,iv:z0EwEaWVip/raOFMmySbbKc4gCDLJUh8BxA9QaMdkos=,tag:tXKu0p0ts8hXLHBWWvPBEA==,type:str]
        namespace: ENC[AES256_GCM,data:ftKpIqvBLuw=,iv:9CO8ax6PFfSRn++dyomkmCjXfNHTtZwXRDW/LVxw1i4=,tag:MjBXAPshn2XeQAa8SQXRMQ==,type:str]
        port: ENC[AES256_GCM,data:UUQ=,iv:e8rJsPdJjYDImAd6GBEgO5orlCnTbh9EnshWmGzbTMA=,tag:XboWSQfQKjTTzD4peqcpIw==,type:int]
        entrypoint: ENC[AES256_GCM,data:FfI1n+I=,iv:Qr1Spuz6idVExspvUO47qdl3ugesxws7PD+CDtS8Mrk=,tag:0Pwwfd5RKfH6boVSak4vxA==,type:str]
bitwarden:
    namespace: ENC[AES256_GCM,data:PvJngXxpbYjt,iv:QHkqO0roNK3WApLogpUD4qUUEqmPMRqXhvv3TfR+GqA=,tag:ebifuxdmZ5I8RtW0lXlfiQ==,type:str]
acme_dns:
    namespace: ENC[AES256_GCM,data:DnMDIcmiGKs=,iv:g+Bek2Vk+ubFPah0bFAW+jZ5cwNNSCLVokz/K7t3XCs=,tag:IKUO1VaBbkc0FDEXK+CV+Q==,type:str]
    domain: ENC[AES256_GCM,data:psifFXihDLtpyzsf,iv:P2crS76REcn8gk7H2g1RRJgvwzvvdKi0iGhpnSKFCQg=,tag:2g7TXVoImo1jd9SFBMq9lg==,type:str]
    email: ENC[AES256_GCM,data:9MIbvgjFW/7ew2XZXw==,iv:rxFcQE7VoXih1MEuCbpSs1ywT1gGA43Ks9raOFq2oPs=,tag:kqSJU1hx/uPxqLeH0fEzMg==,type:str]
    public_ip: ENC[AES256_GCM,data:OKaPpdw7YJQ=,iv:paz1dibB6RTv5kJDOQpM2mgjK43sG9tXUmIderwYzP4=,tag:chjo3XCFdLyWhY6rhKCGiQ==,type:str]
ceph_csi_rbd:
    cluster_id: ENC[AES256_GCM,data:TIBQTtdbfcpWk0l2LnIR+rlfInb6eDwTKn4AB1CPeUlrG3BD,iv:pvSDeESQl41NaVPTya/P+95Xkq4o/NAoedRla6v11x8=,tag:UsC2bZJbGDfNMKiry6dqOg==,type:str]
    mons:
    - ENC[AES256_GCM,data:HDv57r648xnmqQ==,iv:HgGW/J9yO9P9T+G2sPieo/U1xetpdQp9K+bApBASK68=,tag:+Fl6iW6VDC68ghwjoNEg0w==,type:str]
    - ENC[AES256_GCM,data:KzIXHokQAGAN,iv:rxYYw9KZ1hqx1WMpzx5nfl0mmQaTO9UdwGS9PQwPUUA=,tag:uwvvlO0czNr1QFykEg6uHg==,type:str]
    - ENC[AES256_GCM,data:/x/+cT1YBkLk,iv:sq7n8+aHUe3Z4om1rNAHW8V67n/MfLpXVdme/rzCT7M=,tag:gmt9Jni4kIA30a8Cy69G0Q==,type:str]
    user_id: ENC[AES256_GCM,data:ni0W1cw=,iv:t+3Tb9SmtDJwtbcR55YLT/+6RKlnSOSGT86OXM5MDHo=,tag:Yb2QaV4ThiHgKcByHy8j3A==,type:str]
    user_key: ENC[AES256_GCM,data:OPWaqKm8hjphX8WhSQYA7/ukyQMjeZtj39vtwDXkph+0j+hW8wJM2g==,iv:7kKkT4t0InRyHk4ByqQGC2uvpZ5TAlLyMEXrUjw+dPY=,tag:GkfuuegR4AdiQXGk8SMK3Q==,type:str]
    storage_classes:
    -   name: ENC[AES256_GCM,data:UMw5c9k0aTEhkQ==,iv:xqhtYsDl7GqlevAd82yxDemCjax6hMlRQSPtq2BAxo8=,tag:+VHFgNzMk9tB7QPm2SQXPQ==,type:str]
        pool: ENC[AES256_GCM,data:Mjuj,iv:AxxYnWUTJRsG+/zZAcWpjYMEiR1DoXZmpd/cg39WRtU=,tag:zVMUvObmHmOQEsx0tGnlOw==,type:str]
        default: ENC[AES256_GCM,data:7WwZog==,iv:8RWEO78r/OTvIvr3DOojsInGirjCT2u3LCdcnFjoSww=,tag:b8C7QoE55EoVD+igVko07g==,type:bool]
        fstype: ENC[AES256_GCM,data:RNwF,iv:qAw4crbnjHO7np3L0e1kef2KaAB3uJy9WEtou+IuOEQ=,tag:kD35egjLjc+XGCtkNhKMeQ==,type:str]
ceph_csi_cephfs:
    cluster_id: ENC[AES256_GCM,data:03O2tkZ2cyCEBd509vhpLn9g5QYboJUPtk4uq8Ohjt9CUTJi,iv:teAt/m5qV6us7QKREW8NkH3eEtYb1h0qSX8RjQwLHYs=,tag:F9WarEjv0kyqyZhHXjnLTg==,type:str]
    mons:
    - ENC[AES256_GCM,data:01BWSiZ33/4Lkw==,iv:pCzy3Qk9OUbj11n9vbzNnMCXL/Z89I8xxZw+fpcN84M=,tag:XFtK7H4dzCzvVrJG9L6i0g==,type:str]
    - ENC[AES256_GCM,data:9lnqI3RTYt5u,iv:+a1ewsMlQbNjErdztAkbeO9lGP4p9urGcMvsGhmtdLw=,tag:IaGnHCEBCPeiYsJIsE8WXA==,type:str]
    - ENC[AES256_GCM,data:pvqngo98VX68,iv:hd4XbNxi44XRNTYQ2KuovrK60sOgH6lxcKMbvxd0AHA=,tag:SAv3Id+5klRvj9gWiPfGmw==,type:str]
    user_id: ENC[AES256_GCM,data:ChuFzjc=,iv:26U6zKQujG2C2MTfOv7na6xpII6OfhVdNRJ0q5dKsUA=,tag:KRW3TFoBQApQWroMjQDPMA==,type:str]
    user_key: ENC[AES256_GCM,data:B1HAbSULjF7pKxf1cBEFQRV3shwrwzgxFeMk7kjlxEtsdBZO/ex/6w==,iv:dAPwqte3e+BiawyOGOYJC5qihSUrEvY7b8DS1UM7FOE=,tag:6b8EWlLJg9Kg83GVjIDDDg==,type:str]
    storage_classes:
    -   name: ENC[AES256_GCM,data:TDOlC2TgIQBImbI=,iv:2TwPpMBlRCY1o6FQbYpf8QKa1pB/DjIrPcaYEnSOsNs=,tag:TknMsaOa1lOzIR9Np9WG0A==,type:str]
        fsname: ENC[AES256_GCM,data:I72to9vdJA==,iv:ryZDN/lH3jghZhyCCUdgvbHUDU7KlqHhz4mqhXOfwow=,tag:aHU9OSpjRdnSOMxgMQor+A==,type:str]
        root_path: ENC[AES256_GCM,data:iw==,iv:vXJu2OwPLa7npkvQBRaE/DKAKrmek76alAktFgyBf3o=,tag:ov24Pfg2fKpmMnSn2Is4iQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-09-08T21:27:51Z'
    mac: ENC[AES256_GCM,data:LQeSU2pGh8JSgxNL4LqfbEqLO4mAdkB5Q7EQgWK0Fu8Aki0DUWrd8CorzRlwAj3Zux6rbMe/uCOUEA/evYWkkYf9LjG7po1fivLAab8LxrdEnvSB5HO+HBT7CAJHg/2AXN9TqBRSOpHRaTUJdo02eXzH1WcT2meuAaZj1SNEOls=,iv:AQ+4y+WYTFZfYZ3Enk+vel5JaevThBnuLxzJKM6ihqk=,tag:hcGOsQzEvmhIalsU0i5fGQ==,type:str]
    pgp:
    -   created_at: '2020-09-08T21:27:09Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8+hman75/nUAQ//dmVZtmz6pAK1bglOkaa06BYQAJq1B+RvPn3k8AInv1jw
            LLZOJkRGBY41+C4HHuStQt/TtZVwRJIOTNA9AwpLUMV7c60AO6K+aMueUrITegvy
            idHhVFu1nMVIELnYBLLx7fuxlbJqRjjbc4WtU7XZd4cCS8B7ZE1LzoB3fPdK+TEn
            3TxsWIHr/GJ8319pri5Ql/G7Bc/+n6F+8HT0jc5JKg9M2IglSZ4M9mMV+hj1GYpR
            8jWlM4AIeiWi1nvBCkgISeun0A/OWYg5FZayufMnBdqoYBu//jtgUSamlp26WV8t
            yC3iugTT9uOOyW4TdgdHPjXb+UT9Zu4Ly7IgjXh/ymQ+JJwKnKBcyh74jsVs6oTR
            sRiWkhAPRWFNvAbE+6PSZbIbuQcideNLc1OKLU20FLcBvleCg+l4LuK4C/BtegyQ
            1PauOY/nzjqPfvA1oYFuzfVTptibhwnR2eVFRUmMsOVeTPeiuoath61XLLnOP3GN
            LhnylDw8YWAwus+HqLR9cViVsz/2/uxGLjKXF+HIUlWBgtbhPaq6II7us0CheuhM
            KubhHyJ/VeOKkll0Dzb3YERX2tk4XbjNzGRVaXQetg0lEZR/ezW/yklm97RUUgG/
            f64dW2JwNltNPmi1VpN/eY5UIroJyfz0fiGruP3qm2JjO4tr0qAs9grF9fIFI6fS
            XgE1aNuqeaPCc46/G54sbDI/TlUhcvnlQ5qU6I93W8ZW47CyYO2wb3TY0xvRbt+m
            cRax0LFGI6Yf4Ya8fGtvsk1L58jBWFYfHjQdFX+Tij8m8SWGPaZmMHDGKn8yevM=
            =V09O
            -----END PGP MESSAGE-----
        fp: 211FA1AE58F975F266A3E42E3CF239734CDBFD58
    unencrypted_suffix: _unencrypted
    version: 3.5.0
