kapp:
    namespace: kapp
metallb:
    addresses:
    - 10.0.9.1-10.0.9.19
    secretkey: ENC[AES256_GCM,data:ZBronGWEmwht9dNHVD7hBTk4+bbfOH6h9zl9UZ+L6LYw8WftPPyHc4yQ6sE5Hi7PButEh23iErjkjTjLQJAfeIvpMJWMSIRvSCjGw9meGanvwX/zrxhRALU/wh2f7fNAiNMRj6RUZGfp9jz/xGc8M8XGXuU=,iv:bDUue9r2yGQrmkjjrBBcHwvmKwZEN6OXdozFLxUi6Pc=,tag:hfdHFXPoILdB1z4Is/e+sQ==,type:str]
traefik:
    dashboard:
        hostname: dashboard.traefik
        users: ENC[AES256_GCM,data:t6RCYsGFk6dJevic8OT6slDpFFS1dUdqqW8ZSDjitDVdj3dz17c16fVPNvP0lxgy8JNMimYxZb82iSnRCr3QaQ==,iv:3kk5vbl6te19OLAmsoxFsjs/Lz/5NiSH/OpkJCxPAdw=,tag:fkJA7TNTG0yFThZ8XJb7aw==,type:str]
    ingress_routes:
    -   name: bitwarden
        uri: bitwarden.traefik
        namespace: bitwarden
        service_name: bitwarden
        service_port: 80
    -   name: acmedns
        uri: auth.traefik
        namespace: acme-dns
        service_name: acmedns
        service_port: 80
    ingress_routes_udp:
    -   name: acmedns
        namespace: acme-dns
        port: 53
        entrypoint: udp53
bitwarden:
    namespace: bitwarden
acme_dns:
    namespace: acme-dns
    domain: auth.traefik
    email: admin.auth.traefik
    public_ip: 10.0.9.2
ceph_csi_rbd:
    cluster_id: c28884d0-cab2-11ea-a70f-00163ed49eca
    mons:
    - 10.0.8.105
    - 10.0.8.33
    - 10.0.8.62
    user_id: ENC[AES256_GCM,data:0uM6vF8=,iv:QAip9uW0DT2cbVS4dwZFlZ/Fqk2pizqynwo7B7r+9BM=,tag:o0j/4MUq5blBoVEYm+wGmw==,type:str]
    user_key: ENC[AES256_GCM,data:5GQl605AbMk1/B3n+SmkDi7hNJM8UWHj0k7reG3rHVbdrYd4V9th8w==,iv:ShM8NF2HDEcK+b73QLEMUAZnTgPZc1zOjB2okUL4zms=,tag:U41HUf/CbjhC+cTD6je/+w==,type:str]
    storage_classes:
    -   name: csi-rbd-sc
        pool: rbd
        default: true
        fstype: xfs
ceph_csi_cephfs:
    cluster_id: c28884d0-cab2-11ea-a70f-00163ed49eca
    mons:
    - 10.0.8.105
    - 10.0.8.33
    - 10.0.8.62
    user_id: ENC[AES256_GCM,data:hU2RynQ=,iv:zugEnaonXodTqyhLa+wUTCHn3WQ/KXqOf17ht4v2sCE=,tag:BeD6Nq2bm0/JBffNGcXnOQ==,type:str]
    user_key: ENC[AES256_GCM,data:+T7Oc6hQ8VmZDcXLbyX5Ue5lT3imA6v9D0qbFzEqe7ud95rQ2P0rgQ==,iv:anK2CB2x5nKwCMLY5s2zDISx1PdiaVRz1SKgHqBZlyI=,tag:O4zqo9ZOxHpS6QHCQ07L0g==,type:str]
    storage_classes:
    -   name: cephfs-root
        fsname: ceph-fs
        root_path: /
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-09-06T18:53:44Z'
    mac: ENC[AES256_GCM,data:m4R6qcPzMEldwNI1Cp4enbVhMUdbyVzkDDzpqwdw7ZAqaF21J8/MOuUpFG2/09Tdbl181KLnGDDB3GJc4vqNw+r/xJuL1G2m4QTgQbolx3lwAIQ/aOMfmpwAEMSucRfKqBndvPrpsybfC6g71ourVJJv+Rezhb6WmpCYjqOQjm0=,iv:6w65ycvA2j1JlaFdxDo79M7b6ugrHIzWQiAJn2DN0HQ=,tag:caoDAJBoQhwTy5XAWcq8Aw==,type:str]
    pgp:
    -   created_at: '2020-08-02T19:51:04Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA8+hman75/nUARAAOJ60MwHvhUAH6p3TQ/Cb936RdeAwmycpE5+EbvrU62gd
            OrpAl0mHXhPs08kGo8xlY4xvJJFJddYXJfxFs7Sxapqy1KX/ydbi9aE0ScqSjcEF
            u82hU2YDcn56NnD5P4cXH0kfpBDMoaepOf8HdA0BkulbJgqfRnhQUbgbq3wFBW5E
            MvV458TKTF7aDpDCe3prwlfN2x1rVZ7IjEKus/eJP89YwW7T80MYtUVhR80l2mpc
            Vo+Liqe25KCiFGgpmWwBUG4apMpFX6Xozm1HodrnsK+6l4EfgaUpaOB2tfSD98gg
            Ws2oJ3KVsZPeVHlb36gb0wl2Y61aOmwzeMP3rhJKXUlcGHDyf2TgaMs7IfdwZvA1
            qSaKcK/UU14XGXzFBqfZtLd0wjKR2eP4T6C6jR2whcgq7kkyJzYHWVZuLltueP0N
            8MQUAz92+xr22Od+2AsSsDko2XZTZQxkudPbrv0RmCJKltR7U/lFBMvZ+Pf/MQvD
            0xQS0yQDhcYvAcAXIccmP5G+qOH/bz7tzwreOuEMULQpfwvhlKL09myGS4A3A2RF
            xHxggISS6oMZJFp6JOhDhxK1D5PXXO48eWvzUgXMXwDL4+9xegWAYDcCIbayWEc9
            MZkFm5dXDaJbwuxZ8QGqaYYAnkgeEsx/5nL3u3yHqJs2qLFaSv6HoThkl9wiZw3S
            4AHkLdy3xbHkYM90dJDbjZF1f+FihOCh4DjhetPgm+JEo7Gt4Fzl/YkfAx93m5Rm
            xgr0qWJSJe/56NVYN5Z/UwDx1DorW3rgP+QY4uKDr3ycLuK1rf10E0n/4qN2M73h
            7KEA
            =2POI
            -----END PGP MESSAGE-----
        fp: 211FA1AE58F975F266A3E42E3CF239734CDBFD58
    encrypted_regex: (.*secret.*|.*password.*|.*user.*|.*admin.*)
    version: 3.5.0
