kapp:
    namespace: kapp
metallb:
    addresses:
    - 10.0.9.1-10.0.9.19
    secretkey: ENC[AES256_GCM,data:Q/dMZ/VvZ7392nC/fGwKrC3+UtM3Cozpwg4pdXun1Z1JORt4dnolhGztWCmAmXwnKyJds9v850dt7Z6hsKGA+08Tv7WnPOIFGfAYmbKlXMzYPav5mMdRUdlSTY+S++Dd2+GlA7kLCOjET10qt/CN1CPefZ8=,iv:/0Gh7aEbQCwWCGKHK2Uc/gJIj/eXCDF+dlCTSwgeyUU=,tag:A6m+/C+lQRPgGAhHRhVz7Q==,type:str]
traefik:
    dashboard:
        hostname: dashboard.traefik
        users: ENC[AES256_GCM,data:JtVmTySIjIJizlT64xStf+LqkddgnG2uh1n96KnEaflvuKRWP8lcmWK8vxdm6n9WzahEGIZfEyGNorFInuOU3w==,iv:tX7yJJ3ka9l8YtxovxDFYsA+KIdAiBi2AM0SrvKFhLc=,tag:0xRroOjz4fmXm4hVh6Mo9Q==,type:str]
    ingress_routes:
    -   name: bitwarden
        uri: bitwarden.traefik
        namespace: bitwarden
        service_name: bitwarden
        service_port: 80
bitwarden:
    namespace: bitwarden
ceph_csi_rbd:
    cluster_id: c28884d0-cab2-11ea-a70f-00163ed49eca
    mons:
    - 10.0.8.105
    - 10.0.8.33
    - 10.0.8.62
    user_id: ENC[AES256_GCM,data:bHp+X6A=,iv:VgRPsAlh6DO6k9Cvp23rjXLvJdIKG2RbhLwg0IClMC8=,tag:OyS+rNganKoB6WH6Pz5lsg==,type:str]
    user_key: ENC[AES256_GCM,data:iIk2BYBkdV8B4HzfIYLTvh3yluTzGpRFfx8MJMyTn1w6us0KGRDJeA==,iv:WG5ZzBK+CllYOf6xxWwUSNb8U17JBzu2aeG+eEWNdfY=,tag:oHtkqrlVuD3hXQ2WUzhSdA==,type:str]
    storage_classes:
    -   name: csi-rbd-sc
        pool: rbd
        default: true
        fstype: xfs
ceph_csi_cephfs:
    cluster_id: c28884d0-cab2-11ea-a70f-00163ed49eca
    mons:
    - 10.0.8.105
    - 10.0.8.33
    - 10.0.8.62
    user_id: ENC[AES256_GCM,data:FQ8seRg=,iv:DulHLpLyRkbp3VXu2vjlpw5+N1oZcl/L0k67gb1F5Oo=,tag:nsjKsK6hNINbPLoeT0XaKg==,type:str]
    user_key: ENC[AES256_GCM,data:xw/Z3UTPDEyMjcP8CoXwY/iQYFbeIC8/FkkVRzKnrM4morHoyE5FFw==,iv:i1qnB6CHSNdv1zlYF7Md9yUM2y6mImpp62abcq2HVGM=,tag:3fxVBWC+feHWu1088KygjA==,type:str]
    storage_classes:
    -   name: cephfs-root
        fsname: ceph-fs
        root_path: /
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-07-30T00:41:57Z'
    mac: ENC[AES256_GCM,data:XJqQQGwkaFqKmzgdsHXx5fZ9Q+h/qkvyzFrcct031ovFp05t0O8xzrbTHl6ZHoChKfeXGjJ/4K6K0n8kbvRkdu4F39y3oxoea3hGAnOX8N3HnkNzAFZ2oXjYnEkzxVU12FerwHJLlv0AG8RQhlwSACI/NuOru1GVnsAwAd5uEHI=,iv:NU0LLMMYeImqdfMbUv/mwBN2brww822Rj29NBS5ZBCI=,tag:C7U0kfVB30jawbzlv2buDw==,type:str]
    pgp:
    -   created_at: '2020-07-22T03:01:24Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA8+hman75/nUARAAuPAaoTf+bI3AQzRmqkJn9b16mgE30RhTIVxlJJBwR9uv
            oet+tdeGyQcZ/z3WqHuFkvjvA+ir+Vvatw1QRitviSY0cv1pakLtG8Dmuw4SNRTW
            hWaIDiMaipaBEi6mBWopWkb7F5w6FJwXeBL4Tq0AErWAvVVgOdBVtysjNm9+QtHE
            TAR8DOxKFHnq6U0+qjDCZsKq6XAKGFopn/mcTEXzhajmnX5HS4upXLmbd0B0l8iG
            YnsRMjk4FO1cTZP0HPPXUCbF6q2i7aXhiiLDyzy/7kkuk4G+NiLs7vNmWve7Jo2q
            e+JglgyEKb49tzp38CWNJ+Y+9Ae4iyjlvLUleeSx5CmINulNW/nne7U7rSXAoJKM
            vjk16i68azmuE7SjOu4sM7Wrf+8NiFNZPh22jQoo8cLi7WNzSgxAdndsfv2slje2
            8dxX5k1avaRh2lb3ymQdOwpjv7klgOhBzoSaVSIkqbvRLksOtQJbBS8/sxVvm29L
            t4sKrVenc+AsZNLfHQJodbcRv+S3Y3uw3zfwnx/09oMgiY+q5UsEPkvtWN8qaFE5
            +aUlo5nmYgrlhNNWpo5Rju7Kp7qUX8KpoRrU4UQ7IQkSko9AZz/8Q54tWFPRb7Yr
            aeqtd47Pnl3lZGDKIZe6DKG9qKKZ4RKo2OU1TONmyile2OeJn+WNZFstCXjxxTLS
            4AHkfzIVq5l+Fe847f23pvuNV+HtIOA64LzhybTg9uLgKRfj4ELlapx4Bkvz5qTn
            LPNKY+q7HCNc1KcZYFEIcG7fpuB04JHgt+SmMR4Wcad7nKsxrkNYn35n4shbHqvh
            wiwA
            =ZvDt
            -----END PGP MESSAGE-----
        fp: 211FA1AE58F975F266A3E42E3CF239734CDBFD58
    encrypted_regex: (.*secret.*|.*password.*|.*user.*)
    version: 3.5.0
