apiVersion: v1
kind: Secret
metadata:
  name: acme-dns
  namespace: cert-manager
type: Opaque
data:
  acmedns.json: eyJ0cmFlZmlrIjp7ImZ1bGxkb21haW4iOiJ0YmQiLCJwYXNzd29yZCI6InRiZCIsInN1YmRvbWFpbiI6InRiZCIsInVzZXJuYW1lIjoidGJkIn19
