#@ load("@ytt:data", "data")

apiVersion: v1
data:
  secretkey: #@ data.values.metallb.secretkey
kind: Secret
metadata:
  name: metallb-memberlist
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/component: speaker
#@ if/end hasattr(data.values, "sops"):
sops: #@ data.values.sops
