#@ load("@ytt:data", "data")
#@ if/end data.values.traefik.dashboard.users:
---
apiVersion: v1
kind: Secret
metadata:
  name: authsecret
  namespace: traefik
data:
  users: #@ data.values.traefik.dashboard.users
