metallb:
    namespace: metallb-site2
    secretkey: Shh it's a secrete
    addresses:
        - "10.10.10.1-10.10.10.10"
traefik:
    dashboard:
        users: dHJhZWZpazokYXByMSR6M1BiVlpIVCR2RUtFdzEzdzlyZXZzbHpGSkh0UHgxCgo=
