kapp:
    namespace: kapp
metallb:
    addresses:
    - 10.0.9.1-10.0.9.19
    secretkey: ZDNKSTlURHNoVVBXYTMxa0x6VWg5aHM2VlZaOC82dTgxS2Z3dGFWMlZVNllyamJMa3ZiU0tzYlZqdVdaSGd5UFF5ejhiQTh0MytuOUtZVk53NXVvMAo=
traefik:
    dashboard:
        hostname: dashboard.traefik
        users: dHJhZWZpazokJGFwcjEkJEprR3JXS3R2JCREWm9aQXJveWJpUDcyN3NCMEs2cGUwCg==
    ingress_routes:
    -   name: bitwarden
        uri: bitwarden.traefik
        namespace: bitwarden
        service_name: bitwarden
        service_port: 80
        insecure: false
    -   name: acmedns
        uri: auth.traefik
        namespace: acme-dns
        service_name: acmedns
        service_port: 80
        insecure: true
    ingress_routes_udp:
    -   name: acmedns
        namespace: acme-dns
        port: 53
        entrypoint: udp53
bitwarden:
    namespace: bitwarden
acme_dns:
    namespace: acme-dns
    domain: auth.traefik
    email: admin.traefik
    public_ip: 10.0.9.2
ceph_csi_rbd:
    cluster_id: c28884d0-cab2-11ea-a70f-00163ed49eca
    mons:
    - 10.0.8.105
    - 10.0.8.33
    - 10.0.8.62
    user_id: admin
    user_key: AQDE2xVfOiA9IxAAkAHRNrkvx6310BklqabzkA==
    storage_classes:
    -   name: csi-rbd-sc
        pool: rbd
        default: true
        fstype: xfs
ceph_csi_cephfs:
    cluster_id: c28884d0-cab2-11ea-a70f-00163ed49eca
    mons:
    - 10.0.8.105
    - 10.0.8.33
    - 10.0.8.62
    user_id: admin
    user_key: AQDE2xVfOiA9IxAAkAHRNrkvx6310BklqabzkA==
    storage_classes:
    -   name: cephfs-root
        fsname: ceph-fs
        root_path: /
